# Autogenerated wrapper script for Mesa_jll for x86_64-w64-mingw32
export opengl32sw

using Zlib_jll
JLLWrappers.@generate_wrapper_header("Mesa")
JLLWrappers.@declare_library_product(opengl32sw, "opengl32sw.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        opengl32sw,
        "bin\\opengl32sw.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
