[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "2bd89bc65214044135271cf84cd543e2f291bcb6"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "79c541a9c05eb6d5c3994c4785d97ccee6dbd159631fe6d1b000969eed30a00a"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "1de1ae525b47a663bb076a9220d0970dd054b4d3"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "dfffd13497ec5868d051fcd89b5c10a36a311264aba2d61eca12728f3c631c1f"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d85dfd10953bf68dbfd48fae3000dd93b0cfcdc"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "47ec1c47cd167fae2c3c17a2deb7800b1d10690a3195ea14931780fc14521346"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.armv7l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "674994382409c75b03492ae531a0c5672e79b15c"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "40d70a5fd0f5dc835f0becbbd172cdfe98d773acaa9af6d90065fa21f4505ff9"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.armv7l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "3af1309292717fc4bea30ddecf34b9e360212521"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "0639a9dba6575acec1d1a2e27d632fc87b24e973178e7ebe60fbe5a71e68d515"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "63d8d259c2222e75769c1d47434838255d4f1205"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "6ae917dd66b2482c8434ad9c3e79aed6964be602bc4c60732ba50c7ea30d7ee7"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "373f05c05ede908fef1d991ad427b9fb053852b1"
os = "windows"

    [[FFTW.download]]
    sha256 = "6fce5686ee5ca4f231073f7bcc135683df21037e07e808e4d8c6239c0f17c3fa"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "d4d8b063a7a04fa24b47be979b54deddcb74830b"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "4a49e2152fb79b33097f7b9de6ee3c5524dca4e52318de9703fce2c6ea24fa60"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "dee649f498e7cc57f3bd560db70fbe1f70983e9f"
os = "macos"

    [[FFTW.download]]
    sha256 = "55d113c50177dfd3d809e3a2fa302978a6975266423702790b06b78e0d966e3c"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.x86_64-apple-darwin.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "e8fff3113d692608a8bb8ab8492ec2f02a0de103"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "1e702a1d61ebc8e27412bbd129bda1fa7cf5fd9bbe953cd0ad323a5e660966c7"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "35def4ae29d438bdd79fbb5e425f514c46cab5c1"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "cbb5f7660b764037b4b5718d2f3c0c57c1e0644c33f52ebee497fd8eba52ce53"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.x86_64-linux-musl.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "2e9c1263c881d76833a4655af6fc5995d74bd16a"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "96bc0bb2f487b8a56dc9515d4cd3dbbf6e033a4c594eba87ef92372f570851e5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.x86_64-unknown-freebsd.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "777a73414bad2b4d76804c227e3391b5fa808b00"
os = "windows"

    [[FFTW.download]]
    sha256 = "022967d37873b4724191153363ff436609d5fceef2feed7788ef7491d8c25d4b"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.x86_64-w64-mingw32.tar.gz"
