language: julia

julia:
 - 1.0
 - 1.1
 - nightly

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("GaussianMixtures")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
