include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# basic tests

test:1.0:
  extends:
    - .julia:1.0
    - .test

test:1.1:
  extends:
    - .julia:1.1
    - .test

test:1.2:
  extends:
    - .julia:1.2
    - .test

test:1.3:
  extends:
    - .julia:1.3
    - .test

test:1.4:
  extends:
    - .julia:1.4
    - .test

test:1.5:
  extends:
    - .julia:1.5
    - .test

test:nightly:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true


# special tests

# test:source:llvm9:
#   extends:
#     - .julia:source
#     - .test
#   variables:
#     CI_BUILD_ARGS: 'LLVM_VER=9.0.0 USE_BINARYBUILDER_LLVM=0'


# other tasks

coverage:
  extends:
    - .julia:1.3
    - .coverage

documentation:
  extends:
    - .julia:1.3
    - .documentation
