language: julia

os:
  - linux
  - osx

julia:
  - 1       # current stable
  - 1.0.5   # lts
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
