[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "c9082bb165ca8c6a026a46f9c57eb84b1a05b446"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "1a2b82942f4ed09dd4046fafa1551b0549e8488c9ef2f64b9340a14663a79182"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.aarch64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "aarch64"
git-tree-sha1 = "c67d7cde009a24935bf0b798ff86e3b17bd7b553"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "99ce073263c5baef8f7379e7658ac90434eaea6bb7bcfa34282b12c1de5def31"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.aarch64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "armv7l"
git-tree-sha1 = "94e448e9517bf8eedd688e0de11178b0d03b0901"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "bb879565fc03ccc1790739169911b3ceb0e031d9594bbc6b1469872a278c72ec"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.armv7l-linux-gnueabihf.tar.gz"
[[LibSSH2]]
arch = "armv7l"
git-tree-sha1 = "fdbf10c0e6feeb44550be9cadfeffa8e35f26c93"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "3313e3db2de483b1e1a32a6782baab7189f3358601fe06f76dfff6539542e9c7"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.armv7l-linux-musleabihf.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "3c879c73a4211da30136e28494a16997da8d9394"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "3932b5a10b467e70b9165d800e62b8d5f4dba781e76b671b040b0709c06b43f0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.i686-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "46d4b655e21a70bbb7a2bf097184b05f3f52f213"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "7e3a8ad705125376c3f572667969dd94134afa54170a2b84af570c8f396c7480"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.i686-linux-musl.tar.gz"
[[LibSSH2]]
arch = "i686"
git-tree-sha1 = "fed1e4ce4dc1dbc766d3a2647a0a1a2ec34ecd18"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "c4c46681bd746b0fefef844fcf28c1b103d6e7c7c241d636a9125aeaffad9e3e"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.i686-w64-mingw32.tar.gz"
[[LibSSH2]]
arch = "powerpc64le"
git-tree-sha1 = "d35aa26aca0fe0123619eac28322ca6b3cc39e64"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "4de257629d4c568a525b254be30418aaa028ee24bb57eb1908dcbc2cc31064f5"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.powerpc64le-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "9c0a880045b1444b13715e4be1194d77b87e1447"
os = "macos"

    [[LibSSH2.download]]
    sha256 = "6f393182feed9274a328a37bea4dc3cd83b6487f2835ee54b0a4cf3797218b17"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-apple-darwin14.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "6d4906ad8a52d22b3cf4e9e104a46e7c3d4c5fa5"
libc = "glibc"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "b6dac664fc38fca7b9efc937bb182a147a145f4fa5a387c1cc5a21633b3c8ec0"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-linux-gnu.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "713ec4fcaa3ae71e074c240e7a0009fefed3eb13"
libc = "musl"
os = "linux"

    [[LibSSH2.download]]
    sha256 = "beadeb707450eac0710dd209c6fe9466a077c3291f156b47f2d580f8aae89be4"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-linux-musl.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "cd840b221f567a7d53135651ca0d82bccec79069"
os = "freebsd"

    [[LibSSH2.download]]
    sha256 = "2c81475a84a6f4bd1e06b05b258af916d9686061b30dab2e948cb1637f7d739c"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibSSH2]]
arch = "x86_64"
git-tree-sha1 = "f70a0c7c2917e5bde1419ffe4fba6e3f5fe78324"
os = "windows"

    [[LibSSH2.download]]
    sha256 = "07a5c3ac6f4a49428930e1de5f7027db471b2c8a718c69d264286917dfa77d73"
    url = "https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.9.0+3/LibSSH2.v1.9.0.x86_64-w64-mingw32.tar.gz"
