[[FreeType2]]
arch = "i686"
git-tree-sha1 = "3c14a7c05fd35d5e12259cdb2e5e9fbe024e766d"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "315ce309c388c5e9015599bfbd834b304277d0e562da745036499ccb2abcd7f9"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "da1caa6ad0951509531767b6edbb6807bdde8caf"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "9898010432d62e2223e8bad2e4fc6795286bcb4e1e8877311076780f12c7225c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "66f0c42a169d34dff1fc099b6c9496faacaca3ce"
os = "windows"

    [[FreeType2.download]]
    sha256 = "c542f0d519561faf44b33ed3574a36661e214c421dfa2af82295faa37fa9c50e"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "e15fe210ca36f019049f24557c03c5287c00ac4b"
os = "windows"

    [[FreeType2.download]]
    sha256 = "e6cdbc1bbca36cc7346edc88b3db21831b69d57840ddbf93a70cc704f1e2aef8"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "bb31897ad8d71e4a9422da6f57f548024dd3a4ea"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "09c2a0d3aec9a317a4913421dde1226855b879c9a96453d6684126edb62cf915"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.armv7l-linux-gnueabihf.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "5289cdf179ee39ed5c6de094009d63a7e0264ba3"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "b2c341f9a2dbc19e1e6a863f14fbb204e0edce35b5aad2f062e83748b71936b5"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.armv7l-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "feba69e5947b75b4657d43bb8b1ca055df78d143"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8dc12eb875a48f091b43ca79b0c1f8098d0096cbd92d32ad8273805153d642af"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "869e63e913443f9fcc829a42fe4258a6a0b7dec8"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "6f9234b0315e408e9d29e16bff89a5364eb5625dd519eb45747273874392901f"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "1409ac41ce2ca8195d2e7bec3e8d9a6d8f2c4c3e"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "1be8d691464821ebfd01ad3f640df5ed348f709d8d81a278ddbf74d91820f78d"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "6d4a696c716e1dc3c552f345367831ad6db06ee5"
os = "macos"

    [[FreeType2.download]]
    sha256 = "983ce1951718797b76c8d6d26fa63e08417a42e96d311f98a4cbb8a5b043761a"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "745b8d7d1b01fa365709613ead552fb0851cc047"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "4eb61829e71a13fe33a98ebf89283b00b319b4f53f5d8154bb92c1e6e74efa82"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "2e8a250a155439188e6e3a2cc59641dae2ad49d1"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "d6c35fa77a25cde1276d7f1d146b87812daa110d5f5e2cac81aac15d214cff93"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "7ff9517379466c2ff17c2bc63f18cd90f943f387"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8a62c4162e432fa68127d51a63c0acb1d50fc47c41575b3d185c06fad7e5295b"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+2/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
