language: julia

julia:
  - 1.0
  - 1.3
  - nightly

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage;
              Coveralls.submit(Coveralls.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
