language: julia

os:
  - linux
  - osx
  - windows

dist: trusty

julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.build();
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
