language: julia

os:
  - linux
  - osx
#   - windows

julia:
  - 1.0
  - 1
  - nightly

notifications:
  email: false

git:
  depth: 99999999
  

addons:
  apt: # apt-get for linux
    packages:
      - hdf5-tools
      
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
  
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
