[[jlqml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebe1276e152db493f9a5819b106720e89586c030"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "2732078bd2f709ff3274195d57216c729e51210b72b24c5c18dbb04af62872df"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f40fde50f39fac0c1c7c3cf5bfcd62c6acc5b79f"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "70fb88d67d5f33adad2f3c3a1e88eb26b98ab2d8be43eb36f0c9c262fca9d83d"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac8541d39401d806ac645d286399f11a0c1a87e9"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "f16d6422e81d05f8e2a9c63b6916843b169737b428d1d244fa17c32f7f69d318"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[jlqml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4a5318a88ee025f0f0a602fc6b9121ee968bb8c"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "30d23faeba34598f6174ef05aa09c7fac49386bf3a8c3aba8adac97be1a80a43"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "765f1ab4b37fd53dedaa8cb90cd3aa8362af61a0"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "29791135cf267bef0dee263bd12d248e9d3abc4548a324cdc7af21fd1f8aedaa"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b75441c83a1211e2acb0c2ed2809784cdd55a51"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "7982b9f2408d1e3be57b74e9d455d8276000d731a508b60064cc4c9bd6d64da1"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acab6a53c78a971f4ed8bdebdd1703945b643051"
os = "windows"

    [[jlqml.download]]
    sha256 = "5b537df5a35a17f30e17f126c8893052c030d7b7b3f0dcc7cb69f103e42ccb30"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[jlqml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cb354a29e1fa3d1917ecc4b6b88f165ad833dc5"
os = "windows"

    [[jlqml.download]]
    sha256 = "fe5c4f666d941312a56c6d371e3b9e8c52e455505a30278f237e0ce25dac6da4"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[jlqml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3103598d01956f3611edd776712b39e83588d237"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "d9bbea6016344dabaff8017261f8e1061b710d28088db1d763b0aba9cdf349a6"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cc45e9461fd5b70366b0e9004143ae2e324da9"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "a60588c57611b3af351c8b4fc6fa13d7a361a35376d4a0059bb4b597d549322d"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
git-tree-sha1 = "7a69cf2d75b49ba220c22ac644e59d569bbcbea1"
os = "macos"

    [[jlqml.download]]
    sha256 = "56b542e73a66266301f44235994e93b4715d3256d2bb81aa6361624925ce27b8"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-apple-darwin.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e2f1e83eaf83ef2a4f92af43e9aec8dcb941877"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "ff753ec2edcbaf7ca5391c26b478e0c6f75a6c24e65bf25b55493f16195eebfd"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "649409328b8e340782d9a504e112306ee02710fe"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "95315d36823f8ba0b3201fb804cf70a61cd601cda74da60af08f187256ab372f"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
git-tree-sha1 = "7ecbf5ee012a8d26ffb5c7960f24ff81b3fa1b76"
os = "freebsd"

    [[jlqml.download]]
    sha256 = "e2d56bab9538e9ba96c896d97d705b93f4a3c04f6799dcce66bc6fea23a1c618"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9736e00594321ba7034fc3b266a9e9dded33b36"
os = "windows"

    [[jlqml.download]]
    sha256 = "c868ae196acb4743ee7778bc687c1dec2c59db06f1c0f850753755ce94dfcef7"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c22f9a05b689f530499e9c8967fb48052fe29c7e"
os = "windows"

    [[jlqml.download]]
    sha256 = "47d7d2f5896af3bb762b0c222f6200f41574e1aea15b59a75336de44c1859c8b"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.2.0+0/jlqml.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
