# Autogenerated wrapper script for jlqml_jll for x86_64-apple-darwin14-cxx11
export libjlqml

using libcxxwrap_julia_jll
using Qt_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "DYLD_FALLBACK_LIBRARY_PATH"
LIBPATH_default = "~/lib:/usr/local/lib:/lib:/usr/lib"

# Relative path to `libjlqml`
const libjlqml_splitpath = ["lib", "libjlqml.dylib"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libjlqml_path = ""

# libjlqml-specific global declaration
# This will be filled out by __init__()
libjlqml_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libjlqml = "@rpath/libjlqml.dylib"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"jlqml")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (libcxxwrap_julia_jll.PATH_list, Qt_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (libcxxwrap_julia_jll.LIBPATH_list, Qt_jll.LIBPATH_list,))

    global libjlqml_path = normpath(joinpath(artifact_dir, libjlqml_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libjlqml_handle = dlopen(libjlqml_path)
    push!(LIBPATH_list, dirname(libjlqml_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

