language: julia

os:
  - windows
  - linux
  - osx

julia:
  - 1.0
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

matrix:
 allow_failures:
 - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Adapt")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Adapt")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
