[[Opus]]
arch = "armv7l"
git-tree-sha1 = "19c66da48f1b96542e98c8dee0459146e57b1725"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "da393b32dbcfe261a34dd972d59cc1a3b2dd5eb4f77b5999c75044691c732c19"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.arm-linux-musleabihf.tar.gz"
[[Opus]]
arch = "powerpc64le"
git-tree-sha1 = "055af59eb9b80dade1c428959f937f6d1132a5ae"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "0ec6b93cd73f7f0d8c81a7df756bc40b72391499c919ebe68ba3f9a868be9565"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.powerpc64le-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "5ef27b13479c84644db2a228b9993a911108e3d5"
os = "macos"

    [[Opus.download]]
    sha256 = "641d5d4733490325657b2a44d28499a23d8f45b6d4cfbd40c1362f822a43d7c4"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.x86_64-apple-darwin14.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "1445ce9eccf3f8ddbeec8089cd57a03bb1ea783d"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "8a1cf8a24c3473effc84fb42d479dc1b9b6a6b690cd14eb4ca25af08b3a050fd"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.aarch64-linux-gnu.tar.gz"
[[Opus]]
arch = "armv7l"
git-tree-sha1 = "6ad09a0f2fe3536e53943e191c485dd79e9fb0d2"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "a5c8835dc9e6890219c6c6b61af66ce91769032597d85f6d87982749549ffd17"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.arm-linux-gnueabihf.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "907d28faa5285fb88bc38d4d2d7eae976b703232"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "3d38f4408a1509dd6b3466a42ca27c009b56dde74fa164fc865c338584821ee8"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.i686-linux-musl.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "c028c581c28b75ba28e619e2f238768698390676"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "9b00d2274892da7b3816a13b70b27bb9ef1fcf4703bcb1470f2f4a30d4c80853"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.x86_64-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "790a234e4d1492802bb2a1e1c8b21bb072c19147"
os = "windows"

    [[Opus.download]]
    sha256 = "fd239496fa79d0f4c208e98cd130384a5a4c6a76a3b6aa260efc793075bae508"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.x86_64-w64-mingw32.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "01b47757e251569e28353954e79f659c17b2d065"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "c073a5d9f08ca85b5bb63d529c072e23dda4d2db88d99894ef215509e2d6e488"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.aarch64-linux-musl.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "7c089898a57ae5fe21b623d333cc20822efdbf4b"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "0ac71058e4e32345af6faa732bc9bc8f90adf2084e48afe82f100d683de93e32"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.i686-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "f1ff2f9067855c7be4af727e4c8642bc6d7e550d"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "cdc5c4fcc6800cededb33aced7460b3dc5f56eeb7f98c05007448aff39853a19"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.x86_64-linux-musl.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "66c222e54c7cd67a397c7721ace30c8ed248d5f8"
os = "freebsd"

    [[Opus.download]]
    sha256 = "9f05a0a0c67901241b61f6d7d0c8e7db77f82b601ddaa9e72a7eeef28a4433c0"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "d62e807cba289d08539c286cfd22afc096e40e28"
os = "windows"

    [[Opus.download]]
    sha256 = "af9ed56fe36e0c40f5d23d3a71985d97dfc20d962a57e1d521fd13a1cbf293ce"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.1+0/Opus.v1.3.1.i686-w64-mingw32.tar.gz"
