[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "856ec04e9703801a7d3cc848acfecdb7747af05c"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "cda74012e0ea614708c5132e13e9eabf3c1dbace839478b545c5170a0ca43d19"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e65aa87585bb1c7b4f6e9ca9d402e1f6889e242"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "1f86af6164c8f060ca990509042aa089f13f49f757a2a3f51f39b18ad1e6b369"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d95c7172cde1292a1ca5e58f0461eeccd985e0f1"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "2c0f3ebb7d26075ce69e5cb1db75d69936c3f6103ce6f6f7bb8dfc2dc5672729"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.aarch64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "357168aa5acd400a48ec20a75574a4f678bc5c86"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "e3c09dcc6916de01d37f7faf64cb7ea5210028066a705a199e9eeefef792bbab"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.aarch64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dacd34771d50485963021e25e7eb871cba5e7e15"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "73429dbbcbb47a29080fa385abb96a9f3bb83455de3b2f08edeeab5937767628"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "912007774df9b4178a266b517419b8cf3978dcc7"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "77c3268ecf0cadea1ea60cb91506d8f142630d19fec35a60f7bbc4060651a582"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bad88ed95fb6946f3370ce7a43cee93b6acb0e8"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "33d2f9f0383dc1b0dcc5d0a956a8d2b78a8e43c25e3154b0e7124656e023526d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a6b6999a174060f64a390eacf802c1c13d3b077"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "3df646916cc483908697661b6d449b73913ab275034339c36ae9151d7a631f11"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2902512e05b504f0ae88ff7ed22c69b68eacdf7"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "edacc89be272231ce13af5133a6ddafb268f2ba52eadd724f7f249d8080b5a64"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eae3d29274155dc15694eab187761ecd00b33c56"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "4dc937d473fd91a23818b4116f55876afc9aed70bcd21272bdc4cc7f799ed4e6"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f43e601380754d91adc6051e7b75932d70e3700c"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "d76d30d91dc75667dc189990b771fedfa91fd18d4b2cf7574510c0bbbc00214b"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77b401f15aaf2a0cbddaa9275d728d2b955b45bf"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "7b55ceb5446365b75e9d73566e1ea4722998c86d5bab2d4d519f9aa5e2e28cf1"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8ea35928fa0b0f97aaedac42c1ee87efbfee449"
os = "windows"

    [[Blosc.download]]
    sha256 = "9a2614e37f18cc3b88058e52f063d6bdd114958e5934bf21214d472c5948b973"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1197d61bbaf268ad3d246fe9bec82f45c820fa3"
os = "windows"

    [[Blosc.download]]
    sha256 = "565096eeb3faf784a61f785d755f7215d756822734d0c9680b9222c05ea6b641"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.i686-w64-mingw32-cxx11.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "587ef0132d6d4f2c363add47606bd4d4b022a2bd"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "c3a324bcf948246db3ea5384f489446631033eb2b98c7316ca5c32d68e7d5d37"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ce755c1651f533036678865d05e6d7dcba72937"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "dff7ac70ca3e05c55ddccf8965f9c8f583bc6fcf10e5fbfbca51e362755c3a96"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "6ee77244e5383693ca52eb0eee11990056ac25d2"
os = "macos"

    [[Blosc.download]]
    sha256 = "20181d8d3786e87d74d38a17f23f48642e709226c342df9c9afae02354eab92e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a9cedeb9309902889e630027f993ebd6e2c616"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "75e8c5bec8aac44af4945a477a57a21c005a8c6d14e08fc1b467704f57aa4ebb"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dad7076b61af4ac6dcb93ca63064eb18c1d4a503"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "ff07632906aebee23846078a065400b24816b49789bdc3ee8148342a6e5854ec"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1af742cb3cbd8c1488f15d63cee50066e56a729"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "67601808a06f831636a19d92d70d13628fd2f122c6926ab4f4804e41df36eb8d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "351f07b5a1b168430f7a1279e67f72064666dc78"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "dbb08e7b5b1a742ac816d36d523b629ab3ac48dcd3a8683f8426c6e17b830e59"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "2b60c4c9b44779eeb05dabaa66fcab20e85f7fc6"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "8bb1f3606f7e88ffc843269ef1d545307cd2bf52bfe485bbd7c7aca43db764f6"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53b2f3e0c8bc9cd6a292c7c57abc5edddfc81ec1"
os = "windows"

    [[Blosc.download]]
    sha256 = "50aca352a0ab41e4f824e11804433c26ee8d6bc355e4612802597ecb37d25036"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61bd230125082aca872a67bfd4000f27b916072c"
os = "windows"

    [[Blosc.download]]
    sha256 = "fca52a6fe4464da89a93ab92a12b23f2ff06f8e6c9c4e31ce002edea0ab0dd15"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.0+0/Blosc.v1.21.0.x86_64-w64-mingw32-cxx11.tar.gz"
