# Autogenerated wrapper script for XSLT_jll for x86_64-apple-darwin
export libexslt, libxslt

using Libgcrypt_jll
using XML2_jll
JLLWrappers.@generate_wrapper_header("XSLT")
JLLWrappers.@declare_library_product(libexslt, "@rpath/libexslt.0.dylib")
JLLWrappers.@declare_library_product(libxslt, "@rpath/libxslt.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Libgcrypt_jll, XML2_jll)
    JLLWrappers.@init_library_product(
        libexslt,
        "lib/libexslt.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxslt,
        "lib/libxslt.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
