# Autogenerated wrapper script for Qt5Declarative_jll for x86_64-apple-darwin
export libqt5qml, libqt5qmlmodels, libqt5qmlworkerscript, libqt5quick, libqt5quickparticles, libqt5quickshapes, libqt5quicktest, libqt5quickwidgets

using Qt5Base_jll
JLLWrappers.@generate_wrapper_header("Qt5Declarative")
JLLWrappers.@declare_library_product(libqt5qml, "@rpath/QtQml")
JLLWrappers.@declare_library_product(libqt5qmlmodels, "@rpath/QtQmlModels")
JLLWrappers.@declare_library_product(libqt5qmlworkerscript, "@rpath/QtQmlWorkerScript")
JLLWrappers.@declare_library_product(libqt5quick, "@rpath/QtQuick")
JLLWrappers.@declare_library_product(libqt5quickparticles, "@rpath/QtQuickParticles")
JLLWrappers.@declare_library_product(libqt5quickshapes, "@rpath/QtQuickShapes")
JLLWrappers.@declare_library_product(libqt5quicktest, "@rpath/QtQuickTest")
JLLWrappers.@declare_library_product(libqt5quickwidgets, "@rpath/QtQuickWidgets")
function __init__()
    JLLWrappers.@generate_init_header(Qt5Base_jll)
    JLLWrappers.@init_library_product(
        libqt5qml,
        "lib/QtQml.framework/Versions/5/QtQml",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlmodels,
        "lib/QtQmlModels.framework/Versions/5/QtQmlModels",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlworkerscript,
        "lib/QtQmlWorkerScript.framework/Versions/5/QtQmlWorkerScript",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick,
        "lib/QtQuick.framework/Versions/5/QtQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickparticles,
        "lib/QtQuickParticles.framework/Versions/5/QtQuickParticles",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickshapes,
        "lib/QtQuickShapes.framework/Versions/5/QtQuickShapes",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktest,
        "lib/QtQuickTest.framework/Versions/5/QtQuickTest",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickwidgets,
        "lib/QtQuickWidgets.framework/Versions/5/QtQuickWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
