# Autogenerated wrapper script for Qt5Declarative_jll for x86_64-w64-mingw32-cxx11
export libqt5qml, libqt5qmlmodels, libqt5qmlworkerscript, libqt5quick, libqt5quickparticles, libqt5quickshapes, libqt5quicktest, libqt5quickwidgets

using Qt5Base_jll
JLLWrappers.@generate_wrapper_header("Qt5Declarative")
JLLWrappers.@declare_library_product(libqt5qml, "Qt5Qml.dll")
JLLWrappers.@declare_library_product(libqt5qmlmodels, "Qt5QmlModels.dll")
JLLWrappers.@declare_library_product(libqt5qmlworkerscript, "Qt5QmlWorkerScript.dll")
JLLWrappers.@declare_library_product(libqt5quick, "Qt5Quick.dll")
JLLWrappers.@declare_library_product(libqt5quickparticles, "Qt5QuickParticles.dll")
JLLWrappers.@declare_library_product(libqt5quickshapes, "Qt5QuickShapes.dll")
JLLWrappers.@declare_library_product(libqt5quicktest, "Qt5QuickTest.dll")
JLLWrappers.@declare_library_product(libqt5quickwidgets, "Qt5QuickWidgets.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt5Base_jll)
    JLLWrappers.@init_library_product(
        libqt5qml,
        "bin\\Qt5Qml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlmodels,
        "bin\\Qt5QmlModels.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlworkerscript,
        "bin\\Qt5QmlWorkerScript.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick,
        "bin\\Qt5Quick.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickparticles,
        "bin\\Qt5QuickParticles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickshapes,
        "bin\\Qt5QuickShapes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktest,
        "bin\\Qt5QuickTest.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickwidgets,
        "bin\\Qt5QuickWidgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
