# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.3
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
script:
  - julia --depwarn=error -e '
      using Pkg;
      Pkg.build();
      Pkg.test(coverage=true);'
after_success:
  - julia -e '
      using Pkg;
      Pkg.add("Coverage");
      using Coverage;
      Codecov.submit(process_folder());'
