[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "2ecfb730f47cb495bd4f5491438fbca2cab9876e"
os = "macos"

    [[FriBidi.download]]
    sha256 = "e8633a4ae7e7855cff23aef0d231caca57df4ef01ddc6f80e0464022d68d4fe7"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.x86_64-apple-darwin14.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "e80a4224b8826ed49c2427c01a18a5043419e251"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "91d72a5e53208d5c619c88963b7150f60ae026778ecf634aaceef8fd512a4858"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.i686-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "98dc10394a8f40133053b1599bfe85964879fc78"
os = "freebsd"

    [[FriBidi.download]]
    sha256 = "06ac7b94255b0c9dfd3c0249c2967f0981bff5abaa8247b3051f519a3cc296c9"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.x86_64-unknown-freebsd11.1.tar.gz"
[[FriBidi]]
arch = "powerpc64le"
git-tree-sha1 = "0464ff9578f81195b2a0feb9e493e57f5e8969c7"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "5213734f3ae160a828aec400db106aed7feb23fa4ddc32a259c2693d8a57442d"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.powerpc64le-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "570bfcce36364f94e174110da78e93a49029c246"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "6fe14427e950ac9eb1f1536f7b927255f4648eaf978e9c271b4db1453776eb6c"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.x86_64-linux-musl.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "4495315f2c1333959d30831441f22f1edde7a3da"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "da882e3c03bf7d33b1111cb5b3b244d39d6fdb6fd16ee52ca58b363c5bb960d4"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.x86_64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "261953949f0bd7d6c8626090951952bf35ce0003"
os = "windows"

    [[FriBidi.download]]
    sha256 = "37002eabdf694a0e44b4ceaa26b1d23a26338dc3787f7a869dbde56c2ea27bc7"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.x86_64-w64-mingw32.tar.gz"
[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "a2c6d4b24be293d6579b5d421aee237f98d607b5"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "c19d49e566e782d65f6c8b434ec66f1d78f12274ceb5a803fad7aca61e245f55"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.aarch64-linux-musl.tar.gz"
[[FriBidi]]
arch = "armv7l"
git-tree-sha1 = "1f6feec0fec339217874d204cbba59cddf01eca9"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "6b6713643924924ec5e318041c8f33eb89e4ce7fb122f6071c135d65c64652c1"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.arm-linux-gnueabihf.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "9310fd1558f4eb7967d378f65913f758d8af67a9"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "117ad8caf135f4bdfde962fe8983472e20799019500893c2167a1a186918173d"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.i686-linux-musl.tar.gz"
[[FriBidi]]
arch = "armv7l"
git-tree-sha1 = "48b058b0154cf386cac0a977331cdee4ae4dc6e5"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "674eec7a8a81cd7c2a10f5def4fbdc45edc6d8aeb99e3693918855d74bc4ab1d"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.arm-linux-musleabihf.tar.gz"
[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "a0418de8833f14130754524f4fdacf2cc25d4af1"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "e17db133b892d14b84312b22c13c247e9daaa1db0a8bf5bbc72fd19c61756c3b"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.aarch64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "01d7884bec7c02083db9e1fbee82b88d84fb8b68"
os = "windows"

    [[FriBidi.download]]
    sha256 = "93d7b86ca10bb07cb280779cf80aaa1685fc5bcfed8e27d32163b71e15d7a95b"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+2/FriBidi.v1.0.5.i686-w64-mingw32.tar.gz"
