language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
  - os: osx
    julia: nightly

cache:
    directories:
     - /home/travis/.julia/

notifications:
  email: false

codecov: true

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3 --params "PrependPath=1"; fi
