[[Qt5Svg]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f517f15611853eafe2f79f43b6d51a6b7179724e"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "ac32f53e98216145377cd72d8c5fd480ec5fc046bdbbd27b01de6aa2c01c6193"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5Svg]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d92e39a1fcd914bdd969e1f1a8699de53d29f5c0"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "2bdfcf07a79b5be9e8f95119ad9ff2a0c11f6ade0154460fd18a39faa7e3a44a"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5Svg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d095adc34b915d20abcfacbf281f17b369a5dbdc"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "4eb29262f7007816abeae72a5fbfd9eca6dc1cc30b384a75cd5c6d11eb679ce5"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5Svg]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62a0e59eaa06c2883cab1934beb7bd39f32e955a"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "7406176e741e95db1b6cca9c6832ae3835dc7b5a5c090335357623087f7f4173"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5Svg]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a7883f99e0366f4c931fb6d0761c96665644ee2"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "7313ef2a002bdd052721dfc53bcbc81368b175d2b412563f39580df5db07699b"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.i686-linux-gnu-cxx03.tar.gz"
[[Qt5Svg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66e5226192f54e364a2217e63034419c572ea005"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "7e5c8183d1d6bb92636d1f155a0ecd9cb10a0f21b1c1dee22f98b642ccd44b69"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt5Svg]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c3c8e2ed67068819e824c98223f3011baed4ed5"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "eeed65067187dc83ab1c0addf1fdfb5923e9f30861472bdd7bb34013c2eebd22"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5Svg]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "311e48598d913bab40225dc383806e805f62e544"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "97443947dc64d2407ef7b21a3b9e35ce357c75b462011faf1c0f4c6a526b2a29"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb320c8181f064654231d8a8d2f77c6f2c09ecd3"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "7253c4da08da8176266bcb4c33c2824077a9a5282c49bc7f0d4c4f7fbaa96b9e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "110f65ec3fd749867244941108b9fbc66555f839"
libc = "glibc"
os = "linux"

    [[Qt5Svg.download]]
    sha256 = "650b103cf54cc1ddd95669d5716e78c10a8b66fca62152d31068549de79da17e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
git-tree-sha1 = "e0e2064a17954c5ce2705cf856d3b7d928050a9f"
os = "freebsd"

    [[Qt5Svg.download]]
    sha256 = "c82f1b866c30e46139d7f6f3dc629a5bbba16f9f54acf1edb280ad41cf982b0a"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-unknown-freebsd.tar.gz"
[[Qt5Svg]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e087c88182a1e231880794e8acc6a532c3531c8"
os = "windows"

    [[Qt5Svg.download]]
    sha256 = "75f0f26f72ea5d3c4cfddf85aa7b810cda00b102e2a324162d7c60f7e18dc2a1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5Svg]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ca3deb35dd60ea257585eb0eb16360838b4a5f"
os = "windows"

    [[Qt5Svg.download]]
    sha256 = "28e9fecb3227a26313b03213ca8603b38bd26dfa84c0482360a6eb74a0c57a9c"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfdd52734b5ab6a2ae4a7a5126ce27d86d7c1f1d"
os = "windows"

    [[Qt5Svg.download]]
    sha256 = "07496b27ef6feb9c2662bc942e088fdfad2a7251a7cedd8588b58533afbdd637"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2978df4df6e35ab203836f5b0ea412d76f1114b1"
os = "windows"

    [[Qt5Svg.download]]
    sha256 = "c6848106a94521b1a7a275641c6c598913f5579642f0ed45723084cef841f086"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5Svg]]
arch = "x86_64"
git-tree-sha1 = "5af8949822ab62e169e2b1131aaa93a8598fa94f"
os = "macos"

    [[Qt5Svg.download]]
    sha256 = "f66b97a560565dd2a9f83f03c31ae500791fe0e30bb48b539c22f0fb4a370793"
    url = "https://github.com/JuliaBinaryWrappers/Qt5Svg_jll.jl/releases/download/Qt5Svg-v5.15.2+0/Qt5Svg.v5.15.2.x86_64-apple-darwin.tar.gz"
