# Autogenerated wrapper script for LibVPX_jll for x86_64-w64-mingw32
export libvpx

JLLWrappers.@generate_wrapper_header("LibVPX")
JLLWrappers.@declare_file_product(libvpx)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libvpx,
        "bin/libvpx.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
