[[libfdk_aac]]
arch = "armv7l"
git-tree-sha1 = "ddb487b04d162471c8fec2fa88e1bf530047428c"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "9e30a5bf63ef09fcf94bc178dc59b569223045c901f22d4c16bc036a8619b862"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.arm-linux-musleabihf.tar.gz"
[[libfdk_aac]]
arch = "powerpc64le"
git-tree-sha1 = "fd544f9790c6ef005c8bd94892231bff0d49bea2"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "450daf077c2b1011bd41e030e91fc00217e8d9f9d6df9a6fc5fd994732e153a2"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.powerpc64le-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "b9383916d84139afbfba1db347a0a7c0cf7d3ac6"
os = "macos"

    [[libfdk_aac.download]]
    sha256 = "461dec1ce3df4a8e30903b497b60274dafa4cbb4d7c22701475bc4e6d73313ed"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.x86_64-apple-darwin14.tar.gz"
[[libfdk_aac]]
arch = "aarch64"
git-tree-sha1 = "422589de15ac4207fccb5b0ecda2dcbd994d6e52"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "eed669f0dc19dce54613176cb0faca3c4b0b56159f588bf07232adf6a8ee9312"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.aarch64-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "armv7l"
git-tree-sha1 = "482f26165e78c6658744ebfd55563a0aecb1d6d1"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "84b4fae499e28d7db48d2e598df8a879dabd9c5e4ab1ff65d2c91a5e18db3b85"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.arm-linux-gnueabihf.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "c4eec7e1639304f95c0c895c9d7b4fb3c1b2b80e"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "fbd6f156900ab1e0449e1895dc7642dcc8a454fd1009818718fe8bd36332d480"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.i686-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "a48f68b1c246767a37a2515f8f93bab6a4e278c7"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "5bac9e708a2523f73029733ed586bfe4bf9d02a91ce7cf634569f7fd708a9d1c"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.x86_64-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "11f45bd2faec1448101dc273fc308717565cb98d"
os = "windows"

    [[libfdk_aac.download]]
    sha256 = "b859fb8205c6adfbcc57383841f97803729d8a0ec530798e535e9f5531bb0649"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.x86_64-w64-mingw32.tar.gz"
[[libfdk_aac]]
arch = "aarch64"
git-tree-sha1 = "d42b6882e98847bfe754a1198252078e08e29be4"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "440cd67b3efad8fe90dac0d03d34b447fb9b1c0ea6edac09c7d40af84939dc44"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.aarch64-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "862d396d5f126142868619d6732b5c848df215f4"
libc = "glibc"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "8d0f2d37a10f154100a989596e9797b6e0639025ec196996bddbf4c15e98581b"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.i686-linux-gnu.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "131165b82b6cdc3917e946261f8daf5ef411e59f"
libc = "musl"
os = "linux"

    [[libfdk_aac.download]]
    sha256 = "6770012909f815f216c244eea2382c3b42b077462a9927864304a6e69561b33c"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.x86_64-linux-musl.tar.gz"
[[libfdk_aac]]
arch = "x86_64"
git-tree-sha1 = "f0c6b9a7c9508b0a6b3972dbed1a9f9e9b1588b0"
os = "freebsd"

    [[libfdk_aac.download]]
    sha256 = "73a28ddde7f16ddd71deaf6e007bf13402b9d565eec5342a4aa1f048e668a9e9"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.x86_64-unknown-freebsd11.1.tar.gz"
[[libfdk_aac]]
arch = "i686"
git-tree-sha1 = "12ba80e6a948f8c62efc5bbfe8184d8287e8f414"
os = "windows"

    [[libfdk_aac.download]]
    sha256 = "30a65e9433ef66b6f62ce91d45a10d4b28c4b0ebfc35403f1d1545d2cc8df407"
    url = "https://github.com/JuliaBinaryWrappers/libfdk_aac_jll.jl/releases/download/libfdk_aac-v0.1.6+1/libfdk_aac.v0.1.6.i686-w64-mingw32.tar.gz"
