[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "a19daac217fdbf7cc69fa79e808b1661df68a06d"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "0bfc2709e01d74e0fbf499e956b69c33ee3a19094d9e4a5d23b72c75335386ec"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.aarch64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "aarch64"
git-tree-sha1 = "c4148c3ed87c5fadf616f7de5dc6f96658a6e194"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "94672919d72fafebbba47a5267d77d5d33b3e91a5bea8d861d63c2358472b094"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.aarch64-linux-musl.tar.gz"
[[FriBidi]]
arch = "armv7l"
git-tree-sha1 = "fc56b206e7ed1bde892308077b4f53fcdd8602a3"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "47010a1422433657bc0c9a8d09db61f20f2fd43675d2b05cb2d3dd968281d186"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.armv7l-linux-gnueabihf.tar.gz"
[[FriBidi]]
arch = "armv7l"
git-tree-sha1 = "bd60aedff3281b79d4e985613a68eb664df30ff9"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "78290f491634eda2318f9cbf399ec12e670f286bbe49ca3b5508d67668a7437a"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.armv7l-linux-musleabihf.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "9fe1a48b9acd56703dceaf6857701ae90ea658b0"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "9f2b3196cad38d95b299f83d322ea15cb345c156ffbd625213ef06ce7e91d269"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.i686-linux-gnu.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "95f4b39531f89a5bc3854d5847dae4ca6332cbdf"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "5ce7f4e1105fba05933018eacf337fb168319ccd1e9863f109cc229c2454e139"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.i686-linux-musl.tar.gz"
[[FriBidi]]
arch = "i686"
git-tree-sha1 = "09500eed6fe0f9a1fee5af15f03eee2319369284"
os = "windows"

    [[FriBidi.download]]
    sha256 = "403565ca85b543cba8eb7d9e5cecd566d8ac4361a69e7af8eba549ddb462b70d"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.i686-w64-mingw32.tar.gz"
[[FriBidi]]
arch = "powerpc64le"
git-tree-sha1 = "e6a32fab1e04b695a7d067caf92fd4579c849a54"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "fde03eb2af03139526aa8e6afcbc42376f0dc1696ad6fb60d54504b4179fdd1f"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.powerpc64le-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "d3569fceac1fa3e2abd916c5795c75662fc6f263"
os = "macos"

    [[FriBidi.download]]
    sha256 = "37598a33eafbac81412bb9d0dc24d9a9eb31119f87d267b7b8ccf4e9afa6bc08"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.x86_64-apple-darwin14.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "8b5aa917c93435f8e8dfa8de20c145b04a3056e3"
libc = "glibc"
os = "linux"

    [[FriBidi.download]]
    sha256 = "64c27d1dd6caca29ba7c6647915354a8ba4957615adb6d9124f6436e8ec51dfb"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.x86_64-linux-gnu.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "4b1db591d00aaed3e91628f417687f7b1c823456"
libc = "musl"
os = "linux"

    [[FriBidi.download]]
    sha256 = "464e1e07052309f2939a6fff78ccc22769a0241e0aed5322c62ebb2c13aa9fb6"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.x86_64-linux-musl.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "d31610b4cf1357e5d1cf6ccc0aa9f72a5b7e3acb"
os = "freebsd"

    [[FriBidi.download]]
    sha256 = "5a598882255c47b33dd80e4958a2c2e2e06d16baa6480431fa583d3880178f97"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.x86_64-unknown-freebsd11.1.tar.gz"
[[FriBidi]]
arch = "x86_64"
git-tree-sha1 = "18ecb17691fff4b0a002848fa083010d815c1a39"
os = "windows"

    [[FriBidi.download]]
    sha256 = "ad6c27a33ddce86a763af357caa29b91a8d38d8b442f8d0b3c37b3096e448445"
    url = "https://github.com/JuliaBinaryWrappers/FriBidi_jll.jl/releases/download/FriBidi-v1.0.5+5/FriBidi.v1.0.5.x86_64-w64-mingw32.tar.gz"
