language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: 1.4
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
