[[libvorbis]]
arch = "i686"
git-tree-sha1 = "184095b86b8dc73c22c47e5040c6e4f57be4bac5"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "ec455d5da344c5ca6ee06fa689e586abea5e23c60733b6491a51346d346ca32a"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.i686-linux-musl.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "e0991babd2a82245e2c1784ab91f5905f10bd2f9"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "3456e34e05601b71dbb08f5deebce6646803254f70ad8686fa68fa3bc2a69028"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.aarch64-linux-musl.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "590ca5253b3e2d74830d022b71080399e9be0ff6"
os = "windows"

    [[libvorbis.download]]
    sha256 = "5b0dc5f670a5346a0ca084ceb0b2a4d6eb9e690170668c43ea4049fb07e4efff"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.i686-w64-mingw32.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "c2e5e1aaca67dea1283181e2c8ad3d7352eb41c1"
os = "windows"

    [[libvorbis.download]]
    sha256 = "81eb720fe3f35986c5b9ac1a919296206f5d60500ca171dbd6a35f172bd742a4"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.x86_64-w64-mingw32.tar.gz"
[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "b4a9cab830cf61bf0d4507bf1d8699a914b65c55"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "27e547636a31a52f35e4bd75e565faca912d3514495a404a9da915eb754694dc"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.armv7l-linux-gnueabihf.tar.gz"
[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "4691d705f987ebead1b8ccdf8b7f1e197f47c4a7"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "589d5c75b22c706f027331fe1be2777f53799807615a35c2a609e4199679bb75"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.armv7l-linux-musleabihf.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "692de959f5543cb7a14c1ba340befb0ca0825431"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "75d03dc209d463b4d398ee2df98f7a14600ebc6ad67ecad9643dea972f187875"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.i686-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "27239d6461019b165b018a51fe0c6976e7de5e4a"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "0bfc9813e62c660fe32556332921d4eaae5886098cfe8372c430f8c1b84a43da"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.x86_64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "powerpc64le"
git-tree-sha1 = "2013e324599b90591f81cfa26b1ea73eeae98890"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "cab51a2d5ea3179769d87c9d9904c57692d2378ca2faf0b687a03982025d9522"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.powerpc64le-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "94466c451007dfe657daa78ea199180ea11b7c4f"
os = "macos"

    [[libvorbis.download]]
    sha256 = "363705c15efb1f85a2247ce0cfb16c2910e3683906d81ddc69f6ce16eb6f2cc0"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.x86_64-apple-darwin14.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "7905f25750e88c9d174e425e585685e129c9d495"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "d75405935487dba55b87644b3e0cdb8b5e941f0a7f69799bc6ac9f2e93a0833d"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.aarch64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "285d0ce1d11ace56b128ad09b43f0e29ba5c6ca3"
os = "freebsd"

    [[libvorbis.download]]
    sha256 = "b1dbc846d374e0274f30cf0bb92d92326218ead812ab9db9e447b7a0a60d126d"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.x86_64-unknown-freebsd11.1.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "388e46d11df42ff97744d4722932d2c64707e723"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "7ebd052062525ce6d8671b4290bc33d86fa628afe4cc91f3290ae371a691248c"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+3/libvorbis.v1.3.6.x86_64-linux-musl.tar.gz"
