# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
coveralls: true
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
