environment:
  JULIA_DEBUG: CUDAapi
  global:
    julia_version: 1.3
  matrix:
  - cuda_version: 9.0
  - cuda_version: 9.2
  - cuda_version: 10.0
  - cuda_version: 10.1
  - cuda_version: 10.2

platform:
  - x64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - powershell .\.appveyor.ps1
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
