[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "78e9541bd1c5be68a4830d5a86dcf8a4bfae058c"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "faf145c75e61aae8b705e4055224ba5d883af5b92bb6bd80f2bc00291fb5b602"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.arm-linux-musleabihf.tar.gz"
[[libvorbis]]
arch = "powerpc64le"
git-tree-sha1 = "7671284ca5f0c4679659c8ab260f333cf14a7600"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "befae393ccb82be2973a5bb0659f256434412ab28e10e5b7c64939f34c0243b4"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.powerpc64le-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "1e8a16077e70a77098af8c0665e3f469979b7233"
os = "macos"

    [[libvorbis.download]]
    sha256 = "98aba8dd861f3d6012faaae3ee7ed5f13195f06291efc56855f3353d5d23ba4a"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.x86_64-apple-darwin14.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "a7af9b450d8fdd9032c5d992e287ec4ae05a646e"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "09128c859437860094d6c9dbff326ca906831c9f152be0e9653f8aa3c03d330e"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.aarch64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "armv7l"
git-tree-sha1 = "821eae2308c3eb7cc5775c95703731de9ef1ac2f"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "b1f389d1cb1f2154e46616193be3ea5caba7d4b4c5f7897ef4e739c82e31a227"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.arm-linux-gnueabihf.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "66943b24c1247627714d69df4f02911ad91dfa21"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "66ef84234120b62228945c41f895f889c5c161d432e3b2757a80f3b0b5fdd476"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.i686-linux-musl.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "c8d03be740b1073aa383c552d50322962164b4bc"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "e24d8f43af8ab90cc1e441cd7e252b69d7521e2ade63dc76e4882c96f760f833"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.x86_64-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "b489141612a55933633cfe221e50c4ce8b178c42"
os = "windows"

    [[libvorbis.download]]
    sha256 = "6341fb915043ebc2b52750b5d947ddb619044e4d1d1c079d25af1ff14e425dc7"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.x86_64-w64-mingw32.tar.gz"
[[libvorbis]]
arch = "aarch64"
git-tree-sha1 = "8bf7cf6bcf6954a63f9e30937d63449e59972b59"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "247f2a70b3c2a612814c883e61bbef7b9c18442fd539c6bcd14bccd328cbc238"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.aarch64-linux-musl.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "7119c5c787df7cb65dfa892087a6cfc9ad77dfe8"
libc = "glibc"
os = "linux"

    [[libvorbis.download]]
    sha256 = "a76e059764b711c87eaa12882fe52d25091a63dd1d9d7e63be2a794de7c78957"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.i686-linux-gnu.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "f9218a0afad22870a2754a144306523c71498f7f"
libc = "musl"
os = "linux"

    [[libvorbis.download]]
    sha256 = "bd2a2fb93a7e800006b08bb0ae10ea1d0d350c3f0503f988b6b17dad163f47e5"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.x86_64-linux-musl.tar.gz"
[[libvorbis]]
arch = "x86_64"
git-tree-sha1 = "f15113a6152780c9cf8a1ceb8243017dd9941e71"
os = "freebsd"

    [[libvorbis.download]]
    sha256 = "b07bdcec09810c3310cadd3657f08eac7f1c5337958febcec2ef19e274c9427b"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.x86_64-unknown-freebsd11.1.tar.gz"
[[libvorbis]]
arch = "i686"
git-tree-sha1 = "79fefdeb0c8c4037e0e5b92bfb6887374fdaaf9e"
os = "windows"

    [[libvorbis.download]]
    sha256 = "01e909dc5d516e58d8fa98630eb343f6f9421e1f9e23dbcf72a6ab45b5abb5f5"
    url = "https://github.com/JuliaBinaryWrappers/libvorbis_jll.jl/releases/download/libvorbis-v1.3.6+2/libvorbis.v1.3.6.i686-w64-mingw32.tar.gz"
