include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# LLVM with assertions

# asserts:1.5:
#   extends:
#     - .julia:source
#     - .test
#   variables:
#     CI_CLONE_ARGS: '-b v1.5.0'
#     CI_BUILD_ARGS: 'BINARYBUILDER_LLVM_ASSERTS=1'
#     CI_ASSERTS: 'true'


# CUDA.jl

.test_cuda:
  extends: .test
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CUDA", rev="master"));
                Pkg.test("CUDA");'

cuda:1.5:
  extends:
    - .julia:1.5
    - .test_cuda
  tags:
    - nvidia


# AMDGPU.jl

.test_amdgpu:
  extends: .test
  image: rocm/dev-ubuntu-18.04
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="AMDGPU", rev="master"));
                Pkg.test("AMDGPU");'

amdgpu:1.5:
  extends:
    - .julia:1.5
    - .test_amdgpu
  tags:
    - rocm
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.5
    - .coverage
