[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "799a57b8667c759863a38f594330d1ece5c11467"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "538c0be03b2ec55b925ed31c3233cda8703b89efa27ca58b6c886252bce098bd"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.aarch64-linux-gnu.tar.gz"
[[Rmath]]
arch = "aarch64"
git-tree-sha1 = "4c1a561cd5d14d7dafb0a9c3157b0b9f17c842cc"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "42b6ba84b6f80ac4a3865aee3f80b49dcbb36a563d96777fbb99f31cb113c331"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.aarch64-linux-musl.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08bcec87f4c8fc9a15903dbab59960a5e98d2520"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "0b1afcaae2cd1ac755a5cbdd5537317f6edcca67762eda212b4900478f41b96c"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Rmath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa748e9a16d9eaf56aeb0c9d1e37e5409f77cd8f"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "b9a42b6146e2b94134f979a2da2eca4770a0a2a1ca96a3c404df4ed0dd3614c0"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.armv7l-linux-musleabihf.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "5c91f0e052b18563ea50d2e0b598c8fcd0c65574"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "bf48473d317e33c9ac957c871d8cac1a88039528d5ea7d0272cc627c29d7d84a"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.i686-linux-gnu.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "bf96b420ddc05d2f09ca854437d845fdf05f3481"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "8ed892bf953728f030c35d4052b0897f53d3e836b67217a0cfe0616cecccbdde"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.i686-linux-musl.tar.gz"
[[Rmath]]
arch = "i686"
git-tree-sha1 = "c1bbfa2655058d64b35cc78ba005985d01cecd2c"
os = "windows"

    [[Rmath.download]]
    sha256 = "3e7c6fdd257b3f1fcde5aed4621b45b1c0ae160f9c7fa0cd49e728f272089864"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.i686-w64-mingw32.tar.gz"
[[Rmath]]
arch = "powerpc64le"
git-tree-sha1 = "8a188ed636ceaf16381f304dd06ec7ee2788d90f"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "7761cc8d1aee2e20fd494da17cea85ae8de58550a0376dc53ea78c66bd69a1bc"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.powerpc64le-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "10fd2ddd15bea3b831929c032178db55fabe38b6"
os = "macos"

    [[Rmath.download]]
    sha256 = "64a92a633f6158b0a834b579867646dcd7da5e90c1bf8ca4021c2555f28a6833"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.x86_64-apple-darwin.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "93239919eac4ea7558c96cba6b171b1a6f3301a0"
libc = "glibc"
os = "linux"

    [[Rmath.download]]
    sha256 = "5aa531c61e272894f0b3f84d63026af9ebf3b4530ce28ca0db015fde494a7138"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.x86_64-linux-gnu.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "65a4f590502109042aebaad89c107de6e9de6b64"
libc = "musl"
os = "linux"

    [[Rmath.download]]
    sha256 = "e973379a708c1a7542b5e907f1df32f4bee866226dd3552df08628993909735b"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.x86_64-linux-musl.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "37faeb847fe83fa70f00b84fe0772711efb519fb"
os = "freebsd"

    [[Rmath.download]]
    sha256 = "180fa24db17783b779e099b381ef6e26fb2725e9da057ce03a852f76b1c72c6e"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.x86_64-unknown-freebsd.tar.gz"
[[Rmath]]
arch = "x86_64"
git-tree-sha1 = "2626a989333b71ca8866391921268462c63d3e18"
os = "windows"

    [[Rmath.download]]
    sha256 = "05e4824073609636bf988e56ef948f9bbfef873068c555c72d2728ebe97bd328"
    url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+2/Rmath.v0.2.2.x86_64-w64-mingw32.tar.gz"
