# Autogenerated wrapper script for Qt_jll for armv7l-linux-gnueabihf-cxx11
export libqt53danimation, libqt53dcore, libqt53dextras, libqt53dinput, libqt53dlogic, libqt53dquick, libqt53dquickanimation, libqt53dquickextras, libqt53dquickinput, libqt53dquickrender, libqt53dquickscene2d, libqt53drender, libqt5bodymovin, libqt5charts, libqt5concurrent, libqt5core, libqt5dbus, libqt5gui, libqt5multimedia, libqt5multimediaquick, libqt5multimediawidgets, libqt5network, libqt5opengl, libqt5printsupport, libqt5qml, libqt5qmlmodels, libqt5qmlworkerscript, libqt5quick, libqt5quick3d, libqt5quick3dassetimport, libqt5quick3drender, libqt5quick3druntimerender, libqt5quick3dutils, libqt5quickcontrols2, libqt5quickparticles, libqt5quickshapes, libqt5quicktemplates2, libqt5quicktest, libqt5quickwidgets, libqt5sql, libqt5svg, libqt5test, libqt5widgets, libqt5xml, libqt5xmlpatterns

using Xorg_libXext_jll
using Xorg_libxcb_jll
using Xorg_xcb_util_wm_jll
using Xorg_xcb_util_image_jll
using Xorg_xcb_util_keysyms_jll
using Xorg_xcb_util_renderutil_jll
using xkbcommon_jll
using Libglvnd_jll
using Fontconfig_jll
using Glib_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Qt")
JLLWrappers.@declare_library_product(libqt53danimation, "libQt53DAnimation.so.5")
JLLWrappers.@declare_library_product(libqt53dcore, "libQt53DCore.so.5")
JLLWrappers.@declare_library_product(libqt53dextras, "libQt53DExtras.so.5")
JLLWrappers.@declare_library_product(libqt53dinput, "libQt53DInput.so.5")
JLLWrappers.@declare_library_product(libqt53dlogic, "libQt53DLogic.so.5")
JLLWrappers.@declare_library_product(libqt53dquick, "libQt53DQuick.so.5")
JLLWrappers.@declare_library_product(libqt53dquickanimation, "libQt53DQuickAnimation.so.5")
JLLWrappers.@declare_library_product(libqt53dquickextras, "libQt53DQuickExtras.so.5")
JLLWrappers.@declare_library_product(libqt53dquickinput, "libQt53DQuickInput.so.5")
JLLWrappers.@declare_library_product(libqt53dquickrender, "libQt53DQuickRender.so.5")
JLLWrappers.@declare_library_product(libqt53dquickscene2d, "libQt53DQuickScene2D.so.5")
JLLWrappers.@declare_library_product(libqt53drender, "libQt53DRender.so.5")
JLLWrappers.@declare_library_product(libqt5bodymovin, "libQt5Bodymovin.so.5")
JLLWrappers.@declare_library_product(libqt5charts, "libQt5Charts.so.5")
JLLWrappers.@declare_library_product(libqt5concurrent, "libQt5Concurrent.so.5")
JLLWrappers.@declare_library_product(libqt5core, "libQt5Core.so.5")
JLLWrappers.@declare_library_product(libqt5dbus, "libQt5DBus.so.5")
JLLWrappers.@declare_library_product(libqt5gui, "libQt5Gui.so.5")
JLLWrappers.@declare_library_product(libqt5multimedia, "libQt5Multimedia.so.5")
JLLWrappers.@declare_library_product(libqt5multimediaquick, "libQt5MultimediaQuick.so.5")
JLLWrappers.@declare_library_product(libqt5multimediawidgets, "libQt5MultimediaWidgets.so.5")
JLLWrappers.@declare_library_product(libqt5network, "libQt5Network.so.5")
JLLWrappers.@declare_library_product(libqt5opengl, "libQt5OpenGL.so.5")
JLLWrappers.@declare_library_product(libqt5printsupport, "libQt5PrintSupport.so.5")
JLLWrappers.@declare_library_product(libqt5qml, "libQt5Qml.so.5")
JLLWrappers.@declare_library_product(libqt5qmlmodels, "libQt5QmlModels.so.5")
JLLWrappers.@declare_library_product(libqt5qmlworkerscript, "libQt5QmlWorkerScript.so.5")
JLLWrappers.@declare_library_product(libqt5quick, "libQt5Quick.so.5")
JLLWrappers.@declare_library_product(libqt5quick3d, "libQt5Quick3D.so.5")
JLLWrappers.@declare_library_product(libqt5quick3dassetimport, "libQt5Quick3DAssetImport.so.5")
JLLWrappers.@declare_library_product(libqt5quick3drender, "libQt5Quick3DRender.so.5")
JLLWrappers.@declare_library_product(libqt5quick3druntimerender, "libQt5Quick3DRuntimeRender.so.5")
JLLWrappers.@declare_library_product(libqt5quick3dutils, "libQt5Quick3DUtils.so.5")
JLLWrappers.@declare_library_product(libqt5quickcontrols2, "libQt5QuickControls2.so.5")
JLLWrappers.@declare_library_product(libqt5quickparticles, "libQt5QuickParticles.so.5")
JLLWrappers.@declare_library_product(libqt5quickshapes, "libQt5QuickShapes.so.5")
JLLWrappers.@declare_library_product(libqt5quicktemplates2, "libQt5QuickTemplates2.so.5")
JLLWrappers.@declare_library_product(libqt5quicktest, "libQt5QuickTest.so.5")
JLLWrappers.@declare_library_product(libqt5quickwidgets, "libQt5QuickWidgets.so.5")
JLLWrappers.@declare_library_product(libqt5sql, "libQt5Sql.so.5")
JLLWrappers.@declare_library_product(libqt5svg, "libQt5Svg.so.5")
JLLWrappers.@declare_library_product(libqt5test, "libQt5Test.so.5")
JLLWrappers.@declare_library_product(libqt5widgets, "libQt5Widgets.so.5")
JLLWrappers.@declare_library_product(libqt5xml, "libQt5Xml.so.5")
JLLWrappers.@declare_library_product(libqt5xmlpatterns, "libQt5XmlPatterns.so.5")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll, Xorg_libxcb_jll, Xorg_xcb_util_wm_jll, Xorg_xcb_util_image_jll, Xorg_xcb_util_keysyms_jll, Xorg_xcb_util_renderutil_jll, xkbcommon_jll, Libglvnd_jll, Fontconfig_jll, Glib_jll, Zlib_jll, CompilerSupportLibraries_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libqt53danimation,
        "lib/libQt53DAnimation.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dcore,
        "lib/libQt53DCore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dextras,
        "lib/libQt53DExtras.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dinput,
        "lib/libQt53DInput.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dlogic,
        "lib/libQt53DLogic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquick,
        "lib/libQt53DQuick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickanimation,
        "lib/libQt53DQuickAnimation.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickextras,
        "lib/libQt53DQuickExtras.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickinput,
        "lib/libQt53DQuickInput.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickrender,
        "lib/libQt53DQuickRender.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickscene2d,
        "lib/libQt53DQuickScene2D.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53drender,
        "lib/libQt53DRender.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5bodymovin,
        "lib/libQt5Bodymovin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5charts,
        "lib/libQt5Charts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5concurrent,
        "lib/libQt5Concurrent.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5core,
        "lib/libQt5Core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5dbus,
        "lib/libQt5DBus.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5gui,
        "lib/libQt5Gui.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimedia,
        "lib/libQt5Multimedia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediaquick,
        "lib/libQt5MultimediaQuick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediawidgets,
        "lib/libQt5MultimediaWidgets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5network,
        "lib/libQt5Network.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5opengl,
        "lib/libQt5OpenGL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5printsupport,
        "lib/libQt5PrintSupport.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qml,
        "lib/libQt5Qml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlmodels,
        "lib/libQt5QmlModels.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlworkerscript,
        "lib/libQt5QmlWorkerScript.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick,
        "lib/libQt5Quick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3d,
        "lib/libQt5Quick3D.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dassetimport,
        "lib/libQt5Quick3DAssetImport.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3drender,
        "lib/libQt5Quick3DRender.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3druntimerender,
        "lib/libQt5Quick3DRuntimeRender.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dutils,
        "lib/libQt5Quick3DUtils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickcontrols2,
        "lib/libQt5QuickControls2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickparticles,
        "lib/libQt5QuickParticles.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickshapes,
        "lib/libQt5QuickShapes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktemplates2,
        "lib/libQt5QuickTemplates2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktest,
        "lib/libQt5QuickTest.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickwidgets,
        "lib/libQt5QuickWidgets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5sql,
        "lib/libQt5Sql.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5svg,
        "lib/libQt5Svg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5test,
        "lib/libQt5Test.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5widgets,
        "lib/libQt5Widgets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xml,
        "lib/libQt5Xml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xmlpatterns,
        "lib/libQt5XmlPatterns.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
