# Autogenerated wrapper script for Qt_jll for x86_64-apple-darwin
export libqt53danimation, libqt53dcore, libqt53dextras, libqt53dinput, libqt53dlogic, libqt53dquick, libqt53dquickanimation, libqt53dquickextras, libqt53dquickinput, libqt53dquickrender, libqt53dquickscene2d, libqt53drender, libqt5bodymovin, libqt5charts, libqt5concurrent, libqt5core, libqt5dbus, libqt5gui, libqt5multimedia, libqt5multimediaquick, libqt5multimediawidgets, libqt5network, libqt5opengl, libqt5printsupport, libqt5qml, libqt5qmlmodels, libqt5qmlworkerscript, libqt5quick, libqt5quick3d, libqt5quick3dassetimport, libqt5quick3drender, libqt5quick3druntimerender, libqt5quick3dutils, libqt5quickcontrols2, libqt5quickparticles, libqt5quickshapes, libqt5quicktemplates2, libqt5quicktest, libqt5quickwidgets, libqt5sql, libqt5svg, libqt5test, libqt5widgets, libqt5xml, libqt5xmlpatterns

using Xorg_libXext_jll
using Xorg_libxcb_jll
using Xorg_xcb_util_wm_jll
using Xorg_xcb_util_image_jll
using Xorg_xcb_util_keysyms_jll
using Xorg_xcb_util_renderutil_jll
using xkbcommon_jll
using Libglvnd_jll
using Fontconfig_jll
using Glib_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Qt")
JLLWrappers.@declare_library_product(libqt53danimation, "@rpath/Qt3DAnimation")
JLLWrappers.@declare_library_product(libqt53dcore, "@rpath/Qt3DCore")
JLLWrappers.@declare_library_product(libqt53dextras, "@rpath/Qt3DExtras")
JLLWrappers.@declare_library_product(libqt53dinput, "@rpath/Qt3DInput")
JLLWrappers.@declare_library_product(libqt53dlogic, "@rpath/Qt3DLogic")
JLLWrappers.@declare_library_product(libqt53dquick, "@rpath/Qt3DQuick")
JLLWrappers.@declare_library_product(libqt53dquickanimation, "@rpath/Qt3DQuickAnimation")
JLLWrappers.@declare_library_product(libqt53dquickextras, "@rpath/Qt3DQuickExtras")
JLLWrappers.@declare_library_product(libqt53dquickinput, "@rpath/Qt3DQuickInput")
JLLWrappers.@declare_library_product(libqt53dquickrender, "@rpath/Qt3DQuickRender")
JLLWrappers.@declare_library_product(libqt53dquickscene2d, "@rpath/Qt3DQuickScene2D")
JLLWrappers.@declare_library_product(libqt53drender, "@rpath/Qt3DRender")
JLLWrappers.@declare_library_product(libqt5bodymovin, "@rpath/QtBodymovin")
JLLWrappers.@declare_library_product(libqt5charts, "@rpath/QtCharts")
JLLWrappers.@declare_library_product(libqt5concurrent, "@rpath/QtConcurrent")
JLLWrappers.@declare_library_product(libqt5core, "@rpath/QtCore")
JLLWrappers.@declare_library_product(libqt5dbus, "@rpath/QtDBus")
JLLWrappers.@declare_library_product(libqt5gui, "@rpath/QtGui")
JLLWrappers.@declare_library_product(libqt5multimedia, "@rpath/QtMultimedia")
JLLWrappers.@declare_library_product(libqt5multimediaquick, "@rpath/QtMultimediaQuick")
JLLWrappers.@declare_library_product(libqt5multimediawidgets, "@rpath/QtMultimediaWidgets")
JLLWrappers.@declare_library_product(libqt5network, "@rpath/QtNetwork")
JLLWrappers.@declare_library_product(libqt5opengl, "@rpath/QtOpenGL")
JLLWrappers.@declare_library_product(libqt5printsupport, "@rpath/QtPrintSupport")
JLLWrappers.@declare_library_product(libqt5qml, "@rpath/QtQml")
JLLWrappers.@declare_library_product(libqt5qmlmodels, "@rpath/QtQmlModels")
JLLWrappers.@declare_library_product(libqt5qmlworkerscript, "@rpath/QtQmlWorkerScript")
JLLWrappers.@declare_library_product(libqt5quick, "@rpath/QtQuick")
JLLWrappers.@declare_library_product(libqt5quick3d, "@rpath/QtQuick3D")
JLLWrappers.@declare_library_product(libqt5quick3dassetimport, "@rpath/QtQuick3DAssetImport")
JLLWrappers.@declare_library_product(libqt5quick3drender, "@rpath/QtQuick3DRender")
JLLWrappers.@declare_library_product(libqt5quick3druntimerender, "@rpath/QtQuick3DRuntimeRender")
JLLWrappers.@declare_library_product(libqt5quick3dutils, "@rpath/QtQuick3DUtils")
JLLWrappers.@declare_library_product(libqt5quickcontrols2, "@rpath/QtQuickControls2")
JLLWrappers.@declare_library_product(libqt5quickparticles, "@rpath/QtQuickParticles")
JLLWrappers.@declare_library_product(libqt5quickshapes, "@rpath/QtQuickShapes")
JLLWrappers.@declare_library_product(libqt5quicktemplates2, "@rpath/QtQuickTemplates2")
JLLWrappers.@declare_library_product(libqt5quicktest, "@rpath/QtQuickTest")
JLLWrappers.@declare_library_product(libqt5quickwidgets, "@rpath/QtQuickWidgets")
JLLWrappers.@declare_library_product(libqt5sql, "@rpath/QtSql")
JLLWrappers.@declare_library_product(libqt5svg, "@rpath/QtSvg")
JLLWrappers.@declare_library_product(libqt5test, "@rpath/QtTest")
JLLWrappers.@declare_library_product(libqt5widgets, "@rpath/QtWidgets")
JLLWrappers.@declare_library_product(libqt5xml, "@rpath/QtXml")
JLLWrappers.@declare_library_product(libqt5xmlpatterns, "@rpath/QtXmlPatterns")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll, Xorg_libxcb_jll, Xorg_xcb_util_wm_jll, Xorg_xcb_util_image_jll, Xorg_xcb_util_keysyms_jll, Xorg_xcb_util_renderutil_jll, xkbcommon_jll, Libglvnd_jll, Fontconfig_jll, Glib_jll, Zlib_jll, CompilerSupportLibraries_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libqt53danimation,
        "lib/Qt3DAnimation.framework/Versions/5/Qt3DAnimation",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dcore,
        "lib/Qt3DCore.framework/Versions/5/Qt3DCore",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dextras,
        "lib/Qt3DExtras.framework/Versions/5/Qt3DExtras",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dinput,
        "lib/Qt3DInput.framework/Versions/5/Qt3DInput",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dlogic,
        "lib/Qt3DLogic.framework/Versions/5/Qt3DLogic",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquick,
        "lib/Qt3DQuick.framework/Versions/5/Qt3DQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickanimation,
        "lib/Qt3DQuickAnimation.framework/Versions/5/Qt3DQuickAnimation",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickextras,
        "lib/Qt3DQuickExtras.framework/Versions/5/Qt3DQuickExtras",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickinput,
        "lib/Qt3DQuickInput.framework/Versions/5/Qt3DQuickInput",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickrender,
        "lib/Qt3DQuickRender.framework/Versions/5/Qt3DQuickRender",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickscene2d,
        "lib/Qt3DQuickScene2D.framework/Versions/5/Qt3DQuickScene2D",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53drender,
        "lib/Qt3DRender.framework/Versions/5/Qt3DRender",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5bodymovin,
        "lib/QtBodymovin.framework/Versions/5/QtBodymovin",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5charts,
        "lib/QtCharts.framework/Versions/5/QtCharts",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5concurrent,
        "lib/QtConcurrent.framework/Versions/5/QtConcurrent",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5core,
        "lib/QtCore.framework/Versions/5/QtCore",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5dbus,
        "lib/QtDBus.framework/Versions/5/QtDBus",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5gui,
        "lib/QtGui.framework/Versions/5/QtGui",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimedia,
        "lib/QtMultimedia.framework/Versions/5/QtMultimedia",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediaquick,
        "lib/QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediawidgets,
        "lib/QtMultimediaWidgets.framework/Versions/5/QtMultimediaWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5network,
        "lib/QtNetwork.framework/Versions/5/QtNetwork",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5opengl,
        "lib/QtOpenGL.framework/Versions/5/QtOpenGL",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5printsupport,
        "lib/QtPrintSupport.framework/Versions/5/QtPrintSupport",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qml,
        "lib/QtQml.framework/Versions/5/QtQml",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlmodels,
        "lib/QtQmlModels.framework/Versions/5/QtQmlModels",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlworkerscript,
        "lib/QtQmlWorkerScript.framework/Versions/5/QtQmlWorkerScript",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick,
        "lib/QtQuick.framework/Versions/5/QtQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3d,
        "lib/QtQuick3D.framework/Versions/5/QtQuick3D",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dassetimport,
        "lib/QtQuick3DAssetImport.framework/Versions/5/QtQuick3DAssetImport",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3drender,
        "lib/QtQuick3DRender.framework/Versions/5/QtQuick3DRender",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3druntimerender,
        "lib/QtQuick3DRuntimeRender.framework/Versions/5/QtQuick3DRuntimeRender",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dutils,
        "lib/QtQuick3DUtils.framework/Versions/5/QtQuick3DUtils",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickcontrols2,
        "lib/QtQuickControls2.framework/Versions/5/QtQuickControls2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickparticles,
        "lib/QtQuickParticles.framework/Versions/5/QtQuickParticles",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickshapes,
        "lib/QtQuickShapes.framework/Versions/5/QtQuickShapes",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktemplates2,
        "lib/QtQuickTemplates2.framework/Versions/5/QtQuickTemplates2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktest,
        "lib/QtQuickTest.framework/Versions/5/QtQuickTest",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickwidgets,
        "lib/QtQuickWidgets.framework/Versions/5/QtQuickWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5sql,
        "lib/QtSql.framework/Versions/5/QtSql",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5svg,
        "lib/QtSvg.framework/Versions/5/QtSvg",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5test,
        "lib/QtTest.framework/Versions/5/QtTest",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5widgets,
        "lib/QtWidgets.framework/Versions/5/QtWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xml,
        "lib/QtXml.framework/Versions/5/QtXml",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xmlpatterns,
        "lib/QtXmlPatterns.framework/Versions/5/QtXmlPatterns",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
