# Autogenerated wrapper script for Qt_jll for x86_64-w64-mingw32-cxx11
export libqt53danimation, libqt53dcore, libqt53dextras, libqt53dinput, libqt53dlogic, libqt53dquick, libqt53dquickanimation, libqt53dquickextras, libqt53dquickinput, libqt53dquickrender, libqt53dquickscene2d, libqt53drender, libqt5bodymovin, libqt5charts, libqt5concurrent, libqt5core, libqt5dbus, libqt5gui, libqt5multimedia, libqt5multimediaquick, libqt5multimediawidgets, libqt5network, libqt5opengl, libqt5printsupport, libqt5qml, libqt5qmlmodels, libqt5qmlworkerscript, libqt5quick, libqt5quick3d, libqt5quick3dassetimport, libqt5quick3drender, libqt5quick3druntimerender, libqt5quick3dutils, libqt5quickcontrols2, libqt5quickparticles, libqt5quickshapes, libqt5quicktemplates2, libqt5quicktest, libqt5quickwidgets, libqt5sql, libqt5svg, libqt5test, libqt5widgets, libqt5xml, libqt5xmlpatterns

using Xorg_libXext_jll
using Xorg_libxcb_jll
using Xorg_xcb_util_wm_jll
using Xorg_xcb_util_image_jll
using Xorg_xcb_util_keysyms_jll
using Xorg_xcb_util_renderutil_jll
using xkbcommon_jll
using Libglvnd_jll
using Fontconfig_jll
using Glib_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Qt")
JLLWrappers.@declare_library_product(libqt53danimation, "Qt53DAnimation.dll")
JLLWrappers.@declare_library_product(libqt53dcore, "Qt53DCore.dll")
JLLWrappers.@declare_library_product(libqt53dextras, "Qt53DExtras.dll")
JLLWrappers.@declare_library_product(libqt53dinput, "Qt53DInput.dll")
JLLWrappers.@declare_library_product(libqt53dlogic, "Qt53DLogic.dll")
JLLWrappers.@declare_library_product(libqt53dquick, "Qt53DQuick.dll")
JLLWrappers.@declare_library_product(libqt53dquickanimation, "Qt53DQuickAnimation.dll")
JLLWrappers.@declare_library_product(libqt53dquickextras, "Qt53DQuickExtras.dll")
JLLWrappers.@declare_library_product(libqt53dquickinput, "Qt53DQuickInput.dll")
JLLWrappers.@declare_library_product(libqt53dquickrender, "Qt53DQuickRender.dll")
JLLWrappers.@declare_library_product(libqt53dquickscene2d, "Qt53DQuickScene2D.dll")
JLLWrappers.@declare_library_product(libqt53drender, "Qt53DRender.dll")
JLLWrappers.@declare_library_product(libqt5bodymovin, "Qt5Bodymovin.dll")
JLLWrappers.@declare_library_product(libqt5charts, "Qt5Charts.dll")
JLLWrappers.@declare_library_product(libqt5concurrent, "Qt5Concurrent.dll")
JLLWrappers.@declare_library_product(libqt5core, "Qt5Core.dll")
JLLWrappers.@declare_library_product(libqt5dbus, "Qt5DBus.dll")
JLLWrappers.@declare_library_product(libqt5gui, "Qt5Gui.dll")
JLLWrappers.@declare_library_product(libqt5multimedia, "Qt5Multimedia.dll")
JLLWrappers.@declare_library_product(libqt5multimediaquick, "Qt5MultimediaQuick.dll")
JLLWrappers.@declare_library_product(libqt5multimediawidgets, "Qt5MultimediaWidgets.dll")
JLLWrappers.@declare_library_product(libqt5network, "Qt5Network.dll")
JLLWrappers.@declare_library_product(libqt5opengl, "Qt5OpenGL.dll")
JLLWrappers.@declare_library_product(libqt5printsupport, "Qt5PrintSupport.dll")
JLLWrappers.@declare_library_product(libqt5qml, "Qt5Qml.dll")
JLLWrappers.@declare_library_product(libqt5qmlmodels, "Qt5QmlModels.dll")
JLLWrappers.@declare_library_product(libqt5qmlworkerscript, "Qt5QmlWorkerScript.dll")
JLLWrappers.@declare_library_product(libqt5quick, "Qt5Quick.dll")
JLLWrappers.@declare_library_product(libqt5quick3d, "Qt5Quick3D.dll")
JLLWrappers.@declare_library_product(libqt5quick3dassetimport, "Qt5Quick3DAssetImport.dll")
JLLWrappers.@declare_library_product(libqt5quick3drender, "Qt5Quick3DRender.dll")
JLLWrappers.@declare_library_product(libqt5quick3druntimerender, "Qt5Quick3DRuntimeRender.dll")
JLLWrappers.@declare_library_product(libqt5quick3dutils, "Qt5Quick3DUtils.dll")
JLLWrappers.@declare_library_product(libqt5quickcontrols2, "Qt5QuickControls2.dll")
JLLWrappers.@declare_library_product(libqt5quickparticles, "Qt5QuickParticles.dll")
JLLWrappers.@declare_library_product(libqt5quickshapes, "Qt5QuickShapes.dll")
JLLWrappers.@declare_library_product(libqt5quicktemplates2, "Qt5QuickTemplates2.dll")
JLLWrappers.@declare_library_product(libqt5quicktest, "Qt5QuickTest.dll")
JLLWrappers.@declare_library_product(libqt5quickwidgets, "Qt5QuickWidgets.dll")
JLLWrappers.@declare_library_product(libqt5sql, "Qt5Sql.dll")
JLLWrappers.@declare_library_product(libqt5svg, "Qt5Svg.dll")
JLLWrappers.@declare_library_product(libqt5test, "Qt5Test.dll")
JLLWrappers.@declare_library_product(libqt5widgets, "Qt5Widgets.dll")
JLLWrappers.@declare_library_product(libqt5xml, "Qt5Xml.dll")
JLLWrappers.@declare_library_product(libqt5xmlpatterns, "Qt5XmlPatterns.dll")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXext_jll, Xorg_libxcb_jll, Xorg_xcb_util_wm_jll, Xorg_xcb_util_image_jll, Xorg_xcb_util_keysyms_jll, Xorg_xcb_util_renderutil_jll, xkbcommon_jll, Libglvnd_jll, Fontconfig_jll, Glib_jll, Zlib_jll, CompilerSupportLibraries_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libqt53danimation,
        "bin\\Qt53DAnimation.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dcore,
        "bin\\Qt53DCore.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dextras,
        "bin\\Qt53DExtras.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dinput,
        "bin\\Qt53DInput.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dlogic,
        "bin\\Qt53DLogic.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquick,
        "bin\\Qt53DQuick.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickanimation,
        "bin\\Qt53DQuickAnimation.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickextras,
        "bin\\Qt53DQuickExtras.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickinput,
        "bin\\Qt53DQuickInput.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickrender,
        "bin\\Qt53DQuickRender.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53dquickscene2d,
        "bin\\Qt53DQuickScene2D.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt53drender,
        "bin\\Qt53DRender.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5bodymovin,
        "bin\\Qt5Bodymovin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5charts,
        "bin\\Qt5Charts.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5concurrent,
        "bin\\Qt5Concurrent.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5core,
        "bin\\Qt5Core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5dbus,
        "bin\\Qt5DBus.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5gui,
        "bin\\Qt5Gui.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimedia,
        "bin\\Qt5Multimedia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediaquick,
        "bin\\Qt5MultimediaQuick.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5multimediawidgets,
        "bin\\Qt5MultimediaWidgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5network,
        "bin\\Qt5Network.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5opengl,
        "bin\\Qt5OpenGL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5printsupport,
        "bin\\Qt5PrintSupport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qml,
        "bin\\Qt5Qml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlmodels,
        "bin\\Qt5QmlModels.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5qmlworkerscript,
        "bin\\Qt5QmlWorkerScript.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick,
        "bin\\Qt5Quick.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3d,
        "bin\\Qt5Quick3D.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dassetimport,
        "bin\\Qt5Quick3DAssetImport.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3drender,
        "bin\\Qt5Quick3DRender.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3druntimerender,
        "bin\\Qt5Quick3DRuntimeRender.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quick3dutils,
        "bin\\Qt5Quick3DUtils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickcontrols2,
        "bin\\Qt5QuickControls2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickparticles,
        "bin\\Qt5QuickParticles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickshapes,
        "bin\\Qt5QuickShapes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktemplates2,
        "bin\\Qt5QuickTemplates2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quicktest,
        "bin\\Qt5QuickTest.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5quickwidgets,
        "bin\\Qt5QuickWidgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5sql,
        "bin\\Qt5Sql.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5svg,
        "bin\\Qt5Svg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5test,
        "bin\\Qt5Test.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5widgets,
        "bin\\Qt5Widgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xml,
        "bin\\Qt5Xml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5xmlpatterns,
        "bin\\Qt5XmlPatterns.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
