[[libass]]
arch = "i686"
git-tree-sha1 = "f3a2afec9faf0dd215159cd7d255e79c0fc72de9"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "d8cf66d81c9cc8f7441eb35cddb1866934fdd7d0059b1496fa684f9693e35d12"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.i686-linux-musl.tar.gz"
[[libass]]
arch = "aarch64"
git-tree-sha1 = "7b576bc40f5bebf219988e1a009a968be8bf4767"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "c032b00db34df17607e9a48c86ed081c95eb818f7d98c9c5acb983c4e62ca59a"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.aarch64-linux-musl.tar.gz"
[[libass]]
arch = "i686"
git-tree-sha1 = "f0daf2a55d908983815bcf5c63b9d7f437d4b481"
os = "windows"

    [[libass.download]]
    sha256 = "510d54520b3773f73d8d13cd4df762afdad7c9232c987da8c3b85661ced5b7fa"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.i686-w64-mingw32.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "b306fd3c360857c5c223cef0f76377ab2bdfaddf"
os = "windows"

    [[libass.download]]
    sha256 = "58ff33a43e05e092a44f8eff93970f1d29935bffb7f33e46b0055b0ac1cb0b9b"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.x86_64-w64-mingw32.tar.gz"
[[libass]]
arch = "armv7l"
git-tree-sha1 = "07742afc4076945d3a831e190305cb236b3b7748"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "49072851665c5c79885191ea60d92475e057dd832f98aa2b3359543be4bd51a8"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.armv7l-linux-gnueabihf.tar.gz"
[[libass]]
arch = "armv7l"
git-tree-sha1 = "b5ef328dec08532de1d51105ac6cb763d517be0e"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "0920bed7eae6284b70d277b767ab479591ee3acaa457c6e37ee14b17f96aac71"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.armv7l-linux-musleabihf.tar.gz"
[[libass]]
arch = "i686"
git-tree-sha1 = "6200c1e4a18d4dd7f737341631e79719568497ab"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "c7758d05f1315c0f3a391f6ef9da3a5e948f21212e148c1d3d9cac99b62173de"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.i686-linux-gnu.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "b82bbd5825ef933e18b8e7d89c2e056307800159"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "9c88695101f8e979869de465de9763ad77fc00b0d7b02e8d5832af1aa7c4d64b"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.x86_64-linux-gnu.tar.gz"
[[libass]]
arch = "powerpc64le"
git-tree-sha1 = "927f864f89085c93605b41f9a6f75751da183f47"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "4d1f458975365abe1bdeef7a45efac791fbc91de68ca6544fdd896c3c2145f6b"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.powerpc64le-linux-gnu.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "a6d3ce86d902a885e1e092882cb0ddb718aade03"
os = "macos"

    [[libass.download]]
    sha256 = "fbef12a20746cf4562acbd6cb65068066eafc535e464db3239dbaffba3d2db10"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.x86_64-apple-darwin14.tar.gz"
[[libass]]
arch = "aarch64"
git-tree-sha1 = "c0fadc6c5eb6f99d814a223e7619cc1833740db0"
libc = "glibc"
os = "linux"

    [[libass.download]]
    sha256 = "72bd939483ff319a5a16f01beef0ecabeab180bbf6746fb4f44d45655f73e0f4"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.aarch64-linux-gnu.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "0400aeee82d538922624ecf24301398bf43b70db"
os = "freebsd"

    [[libass.download]]
    sha256 = "1be962b12a158c6f49679f51b50b04cf277f53b580c488233d14a0244adf0a57"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.x86_64-unknown-freebsd11.1.tar.gz"
[[libass]]
arch = "x86_64"
git-tree-sha1 = "7e8afbc9faa0bf606ff4257b1078e7eaa23ed103"
libc = "musl"
os = "linux"

    [[libass.download]]
    sha256 = "1f205dcb305499f3c335c21076cf6b33885f286f14f279a233b845b835f55525"
    url = "https://github.com/JuliaBinaryWrappers/libass_jll.jl/releases/download/libass-v0.14.0+1/libass.v0.14.0.x86_64-linux-musl.tar.gz"
