# Autogenerated wrapper script for LibVPX_jll for i686-linux-gnu
export libvpx

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `libvpx`
const libvpx_splitpath = ["lib", "libvpx.a"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libvpx_path = ""

# libvpx-specific global declaration
# This will be filled out by __init__()
libvpx = ""


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libvpx_path = abspath(joinpath(artifact"LibVPX", libvpx_splitpath...))

    global libvpx = libvpx_path
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

