# Autogenerated wrapper script for jlqml_jll for aarch64-linux-gnu-cxx11
export libjlqml

using libcxxwrap_julia_jll
using Qt_jll
JLLWrappers.@generate_wrapper_header("jlqml")
JLLWrappers.@declare_library_product(libjlqml, "libjlqml.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, Qt_jll)
    JLLWrappers.@init_library_product(
        libjlqml,
        "lib/libjlqml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
