# Autogenerated wrapper script for jlqml_jll for x86_64-apple-darwin
export libjlqml

using libcxxwrap_julia_jll
using Qt_jll
JLLWrappers.@generate_wrapper_header("jlqml")
JLLWrappers.@declare_library_product(libjlqml, "@rpath/libjlqml.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, Qt_jll)
    JLLWrappers.@init_library_product(
        libjlqml,
        "lib/libjlqml.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
