[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "af25b6a6b50c5cc00fa70ca5ae8c6d634085d9de"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "093790f9ae8573335550bd4187742452e10d3f75be009d3bc382813342aa8752"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.arm-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "3c41de0860295a9627f2819e7d2e27275796b308"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "ea8e5fae59a6a7f4393a2e5f7ae4930699cac06649722ebffcf447325c6b6ecd"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "96d775fd0a843b550020c7fc15515daae593c105"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "3aaa64b7ab8fb5904e863d3759ea811743f7e47b682479246e61d5b341efa32b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "bd6bd6b33eb5274a7e04e3066a55d2894a29c23d"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "d3447401bfda9970621a07568432eab60644067dfd1f56c718b103082ea4626a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "060c5b3c7386ef4a519b0d3e45380e0b905e0bf1"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "9a7db483ef7347d1a0ab951b45cb144d21e65e046dacc9bca42da048786dfcaf"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.x86_64-apple-darwin14.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "0420080519d84df5ff9c7ce8f0ce44316dbf2be3"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "5480d5569e90b2680ee1811513407eaae1affd74f9c670a47b77719604543085"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "3b1ac54d2f4991bf4680cea08d7a20eefec9c25f"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "a13594eb0d9b4301aa50f6522c6f776b67bc4869f2138c85534545e5c4ba472f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.x86_64-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "e46ad34e7009b9daf63efb82ce272c619fdd33b2"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "6dd2c2a7077b6012b95701f5adc471f4420a37ad2b2c0392199d9bae3e739666"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "0fcb22c9cf73fa73017ba85d8f87cb3c346635b6"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "345b76abc5dbd0a5fcba0288e4ecd9476683e0625582d2f34e1e860b182d0a47"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "3d33100672e23cc08444b4703acb60aa1c2a7552"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "e61c6e4d8c171dd2c0812d5370159e32f90580864bdec12ad91fa0adc84bdbe7"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "f45708b0de346ca796642e81bcea87486b6c32a2"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "644fb4c9d10f1481b07d4fb8f9b6dd9b81cf8994a86cbf5ddf40057825664d83"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "5d61e748e01793599246adec6cae8678311bcc9f"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "bfcce6f189b7e2f445cac9fe8584d1761d1215f40f96d8407557a9536620b6ac"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "6d195e7cf25a75f26e401e44778a2bbc2081fe47"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "f846dadf763976c06eeee8cf325a5f70ef32e6948cfb1c4d7d8c9f958559ecf0"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+2/FFMPEG.v4.1.0.arm-linux-musleabihf.tar.gz"
