name: test-linux
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - 'nightly'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - run: sudo apt-get install xvfb libxkbcommon-x11-0
      - run: xvfb-run --auto-servernum julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
        env:
          XDG_RUNTIME_DIR: /tmp/runtime-runner
      - uses: julia-actions/julia-processcoverage@v1
        env:
          DISABLE_AMEND_COVERAGE_FROM_SRC: yes
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          fail_ci_if_error: false
      - uses: domluna/JuliaFormatter-action@master
        with:
          args: -v .
        continue-on-error: true
