# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

services:
 - mysql

os:
  - linux
  - osx
  - windows

arch:
  - x64
    #- x86

julia:
  - 1.3
  - 1
  - nightly

env:
  - JULIA_PROJECT="@."

matrix:
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ODBC")'
        - julia --project=docs/ docs/make.jl
      after_success: skip

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts

before_install:
- |-
    case $TRAVIS_OS_NAME in windows)
        choco install mysql
        dir C:\\tools\\mysql
        dir C:\\tools\\mysql\\current
        dir C:\\tools\\mysql\\current\\bin
        C:\\tools\\mysql\\current\\bin\\mysqld --install
        choco install lessmsi
        ;;
    esac

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mysql; brew services start mysql; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -O https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz; mkdir mariadb64; tar xfz mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz -C mariadb64; curl -O https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-ga-debian-i686.tar.gz; mkdir mariadb32; tar xfz mariadb-connector-odbc-3.1.7-ga-debian-i686.tar.gz -C mariadb32; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then curl -O https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-win64.msi; echo 'making dir'; mkdir /c/mariadb64; echo 'msiexecing'; lessmsi x mariadb-connector-odbc-3.1.7-win64.msi; fi

notifications:
  email: false

after_success:
   - julia -e 'ENV["TRAVIS_JULIA_VERSION"] == "1.3" && ENV["TRAVIS_OS_NAME"] != "linux" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
