[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "b165dc0d4374efb677b77e48dedb8c6e465dcf0a"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "9de2119840a5a837043c33cdcd697f7ea40037480e6c8841578edcca7e9ff5de"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.aarch64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "aarch64"
git-tree-sha1 = "3fbe0f5a6091dd921501a663ccc61e744ee53520"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "cfc9075a66b4dbd72eb89df9774c58d5fada6cedec7c463eb2ce3eaa86f128df"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.aarch64-linux-musl.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "315ad3149dac3f5677a8773378201a2ce3a169fe"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "b6c7e72671021530124415e7b60cc5477a12559579b17553723cb4bfccc51075"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.armv7l-linux-gnueabihf.tar.gz"
[[Libiconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "047793755e57024811d63673236f82f76447421f"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "012e77fe5e03765a3e02813bfc97c8211a1c73920d40d06ef36e87b58bc8c10b"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.armv7l-linux-musleabihf.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "9943d431af3a1ecd787d488a915b158c404aad21"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "667626d7bb3b515dd16346f840d8692f2d2a102400dfd4cd9337210242e6481d"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.i686-linux-gnu.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "8225fb116d5ae77816d432dd698d11ece4d44ccc"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "d08df37f02cce5b4368cba97380b28e5cca18a66b4a937143dd781bed930538f"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.i686-linux-musl.tar.gz"
[[Libiconv]]
arch = "i686"
git-tree-sha1 = "bc8104e5f18107763ffcaac84de73a9d63cedff9"
os = "windows"

    [[Libiconv.download]]
    sha256 = "a48a71a51f2da80fc7d822fa7e56c9dacd8f61393bc2cb9e1cc166e5e4fe7031"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.i686-w64-mingw32.tar.gz"
[[Libiconv]]
arch = "powerpc64le"
git-tree-sha1 = "acbc95540753b0ec430fc168628521269633d070"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "665578b61d1f7a65de4c926f09fb8cfedac6d4353cc1b3127ac5f4adc75fdf3c"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "d69d9db7a55a8e6bb58e7e83556a7db3182deaed"
os = "macos"

    [[Libiconv.download]]
    sha256 = "0859d9f0894ffce6a2b612cccef3cb1d2fb44e3a553eb5dfb65b661a559a7005"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.x86_64-apple-darwin.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "4db956f08c2211df6e56d2d7dde668e2ff1250ee"
libc = "glibc"
os = "linux"

    [[Libiconv.download]]
    sha256 = "a970ed46021c356b014523982d41eca8c857510efbfc5eb03367c6340eac26dc"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.x86_64-linux-gnu.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "067eea0216bcbb1c83ab9b896b288bddde0aa050"
libc = "musl"
os = "linux"

    [[Libiconv.download]]
    sha256 = "3d11c900287fcbf6641897e8f607d682d5af7c69e911991a9643befb1eb0c595"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.x86_64-linux-musl.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "bee1dab2f4af64bd22009e580525cb02a9e88b31"
os = "freebsd"

    [[Libiconv.download]]
    sha256 = "19aa44a449f4dc015aa5d8c402441e980fe97683de3eb46d0c428a66077ed9e9"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.x86_64-unknown-freebsd.tar.gz"
[[Libiconv]]
arch = "x86_64"
git-tree-sha1 = "66d2a9cb6c6949173d49133603fcf3860785aa8d"
os = "windows"

    [[Libiconv.download]]
    sha256 = "1d6a5fe143d475430edee6a1557557a8b3d512c37ff6c5d2edc3244b1269ba3b"
    url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+8/Libiconv.v1.16.0.x86_64-w64-mingw32.tar.gz"
