[[LAME]]
arch = "x86_64"
git-tree-sha1 = "3ca3753372cbdb821c7cbb72127fd4b4c99d276e"
os = "macos"

    [[LAME.download]]
    sha256 = "71ec7e279b3f75ca334df3241791608c17c5ad83796f2d773449c6b55a862878"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.x86_64-apple-darwin14.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "cadda09aa512c599457562ede366a2e21ed0288f"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "fbfae66ebdcd23eb1da437c3cbf5fba1f3f05d15af4610a221e80763160ca89d"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.i686-linux-gnu.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "6a9c110e7bf4da00c7c0a7e059a3aa00652ee3b6"
os = "freebsd"

    [[LAME.download]]
    sha256 = "332f7213dcb9434a7e7ed49941957520fc2ad23e7993e5eacdecbdf88515700d"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LAME]]
arch = "powerpc64le"
git-tree-sha1 = "fbfa1b5561c71c3ca7ee976488b8d1d29fe1ecc5"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "5f795fc2c93ed554e80f0e0a2cc5b5c472290a12b8df17fef0eb4378099935dd"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.powerpc64le-linux-gnu.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "200f7af91339be921fc3e25ae58292cf3f747d9b"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "9f4559142cd370ad0a1b84b12e78c305abbbef487f908b249ddbf85f82b7bd1e"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.x86_64-linux-musl.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "2834ebdb4e7dd6b881b51adbd5e704e0f796d277"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "62b30787671906cd04499ed46933814528cf96174a32521bc0d0d48528e4fec1"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.x86_64-linux-gnu.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "45cfc00bb8685f615bb28c0c4537a780d4a96d9e"
os = "windows"

    [[LAME.download]]
    sha256 = "7c8058e87a5e2bfda5cd0100d16da4dc58785464a6b2989e2dad30eda13cf349"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.x86_64-w64-mingw32.tar.gz"
[[LAME]]
arch = "aarch64"
git-tree-sha1 = "f39a06b311e1a4c3885935c98e87e3f116211575"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "d06581922873021d6e3db5d2abf7c6377e68992f62be23045a6aa9071ff42f67"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.aarch64-linux-musl.tar.gz"
[[LAME]]
arch = "armv7l"
git-tree-sha1 = "28292580c85992df876a06cb844d1a728bd1265b"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "8ca707997fab3e597a5b449d014a132488bdfdc1634295dcb2e92d2190cfbe6c"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.arm-linux-gnueabihf.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "03fa1f69020cbf7115386739e19c0e2186cf9071"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "a29583b68bc1c91386cfa84428916c842d89dddbf0f58be048fc2db5658fb31d"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.i686-linux-musl.tar.gz"
[[LAME]]
arch = "armv7l"
git-tree-sha1 = "6baf5b10706ff89b4b5fb4f561a7012189fff73c"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "2156d705b722f5c6ea4b5911cd2131a6d51a2019240fa9bdb41311f58ebe3dc1"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.arm-linux-musleabihf.tar.gz"
[[LAME]]
arch = "aarch64"
git-tree-sha1 = "07a261b49826094cf6c5a0f3ec2812cced376774"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "a70bc1d22fd90b7c4aca7ac8f3fcc04489d60a15915bc7eb3c7dfb48f853b113"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.aarch64-linux-gnu.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "58ed3f6723e35f0c6328ebd2eed0dfec454e2db1"
os = "windows"

    [[LAME.download]]
    sha256 = "e73c4f9af4e050958dbe01d825725560188fc321b174278dfd826bfac7b35d31"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.0+0/LAME.v3.100.0.i686-w64-mingw32.tar.gz"
