[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "b064133c829fe8e8bd88b31492bb7f634356dc9c"
os = "macos"

    [[Libffi.download]]
    sha256 = "33a99da7501c6ca76f540992bb51a68ffcd8a6c53b0fdac3bef3a6760ecae27e"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.aarch64-apple-darwin.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "94fe4adb23cf077d8759b0c91e7abb0a959c7e18"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "c3b10dadaa6fa98f60f4048c0c3e7c73fcdc920e86497253ccf58b83304aaea0"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.aarch64-linux-gnu.tar.gz"
[[Libffi]]
arch = "aarch64"
git-tree-sha1 = "8ebcf99cc3ff4ffa3cd16eaa3d03852e5cf42251"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "c59a7c0e93c2902d91b12c40d9c8fdef969d456939ed483363c1ec1c5426e74b"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.aarch64-linux-musl.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a1c98d2b990070692d669a565d6cb63d0a1a404d"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "d4f29ca40f9c80af4f6ff1cd469c32b47f590ea6ba8ddd9f520293aa01406000"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec7235fa53d493bd3e4754c6843df8a8d8943f92"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "7f923a0863828da5659be1d060c6790b99bf3af8407aaa621b0cee45c89045ac"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.armv6l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9736cb3d6c35db45e229b356e30a57383c09e278"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "aacc39ac4f803d2d9226cfbbec9d5b2ef81c3776d9b0a5703a20c282a53a190e"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Libffi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bde42d5c48e5042c70312da88516ebc1b5838aaf"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "5668460f7921272f0453be42f7479831f7d02a9483e1905639b9cb0286ff583c"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.armv7l-linux-musleabihf.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "7e5b5a7ee84ec834531f03e97ea37418ff13e312"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "9c2a64249b31d33736c4af22b68e2abe6665b3708308a6b95d6ba97a599e0f10"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.i686-linux-gnu.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "57f7c31dfd60d3460a97d83c7c174d6bc1856f8f"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "dddbef964652a48c13505e751567e24231c614f2c6b72d6c2ba166896c9f7ae5"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.i686-linux-musl.tar.gz"
[[Libffi]]
arch = "i686"
git-tree-sha1 = "68cbaf18bbde24f3a1c0b39db30a1dd316b3bcab"
os = "windows"

    [[Libffi.download]]
    sha256 = "66a9e6598368a800fb1d76c0c1f4a6f1af9fe12495cea52b9163ec117fed68f3"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.i686-w64-mingw32.tar.gz"
[[Libffi]]
arch = "powerpc64le"
git-tree-sha1 = "b771ad32acb123770b0da7da66411fd46416dff7"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "9072b6467bf6d3c1fe1a30238c2da697ed9df0db4c16a999fad6eb6e4d495bd2"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.powerpc64le-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "8e8476452ea0e1216c95fbb186fb8c12d1cf5c27"
os = "macos"

    [[Libffi.download]]
    sha256 = "6e58fbd7cf1ad0f5af442fe7dc9783229c37d93e9228c90d3f1ca842bfb85831"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.x86_64-apple-darwin.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "f1a54fe617cfa5997fa86c2cb15b93ac1d8c4c24"
libc = "glibc"
os = "linux"

    [[Libffi.download]]
    sha256 = "a24ceaea67a15d2f9559754954516c6ddafff00c07f5827e18cb6ffd7137919f"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.x86_64-linux-gnu.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "4355c73ed1a99241ffd4df90444c3fb99bc7dc58"
libc = "musl"
os = "linux"

    [[Libffi.download]]
    sha256 = "e504fc6f6b620e5a59c2e82d5baa815ee087b90de74ee649933187a891b04675"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.x86_64-linux-musl.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "338752f13c70eff358f0d9d37613add9c04c1928"
os = "freebsd"

    [[Libffi.download]]
    sha256 = "33c8a88fa7b0321f242bcdcab60efbdea4b247faa99478f020f888df11498ad5"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.x86_64-unknown-freebsd.tar.gz"
[[Libffi]]
arch = "x86_64"
git-tree-sha1 = "b3eb54884958b18069b467f349c2766738abc9df"
os = "windows"

    [[Libffi.download]]
    sha256 = "48a91a6f78796218692a79ff8e3be0ce3cbc1fc7ecea9d713a2c4f971896dec0"
    url = "https://github.com/JuliaBinaryWrappers/Libffi_jll.jl/releases/download/Libffi-v3.2.2+0/Libffi.v3.2.2.x86_64-w64-mingw32.tar.gz"
