[[jlqml]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7836cab0e83ba572466f7541afdcb7faa464c7b6"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "0dc6b535419e040d22bad21e62d9eb6fa2f5c188bb48cd2884dd470af7cdd0e8"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.4+0/jlqml.v0.1.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80d1ae25abd62bac6344ecb5c52e9c2e9e4ae720"
os = "macos"

    [[jlqml.download]]
    sha256 = "512d7e353c9ca88ac11c642315fa25bca82f5659bcbe061b1881560344ad6aee"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.4+0/jlqml.v0.1.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a73c51b271b23497235d11afd88730b96cff694d"
libc = "glibc"
os = "linux"

    [[jlqml.download]]
    sha256 = "130167f74aef50cab028139a563455d5ca89ad1a3ed92ec95b54c5673c605fb1"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.4+0/jlqml.v0.1.4.x86_64-linux-gnu-cxx11.tar.gz"
[[jlqml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51d6d77996a6435b0086bcfa0f0503654a80ac6a"
os = "windows"

    [[jlqml.download]]
    sha256 = "ee49359d86d9150cec43db216aaadd07bbcdba34c285e8056d23ae609270dde4"
    url = "https://github.com/JuliaBinaryWrappers/jlqml_jll.jl/releases/download/jlqml-v0.1.4+0/jlqml.v0.1.4.x86_64-w64-mingw32-cxx11.tar.gz"
