[[iODBC]]
arch = "i686"
git-tree-sha1 = "1f53996c9ce31b7624e883a10d4c2e6903cc865b"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "4a115398f0c4349b96ee88d86f3114984ad95b37966f1b04c72f1a98294d7916"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.i686-linux-musl.tar.gz"
[[iODBC]]
arch = "aarch64"
git-tree-sha1 = "41a508d5b70fe67259c1bf73ae3f36459ecc4118"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "222c6a9db4f1b55b3423dcaffe0dea1ba8595d953a58d4df901a2fde78c1f16f"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.aarch64-linux-musl.tar.gz"
[[iODBC]]
arch = "armv7l"
git-tree-sha1 = "4136cb7afb2e64ab691b7a3730613979a1185941"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "7f488243b9a765d84ae0f25e6c4d692cc05960db1e71326789a20966a1279a6f"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.armv7l-linux-gnueabihf.tar.gz"
[[iODBC]]
arch = "armv7l"
git-tree-sha1 = "24241a232eb4580cf4ef564a55ac28f6b36ba3d1"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "b413f050f742e6bbf89da3d243017cd9b19032d54f3fa3cd7e4219921eeb8c85"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.armv7l-linux-musleabihf.tar.gz"
[[iODBC]]
arch = "i686"
git-tree-sha1 = "9cfbc4fae4fb8681df8a6de88972925d1cd30108"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "32bcfca639c45ffc542f51dcf7399546299fde6bc6fcfc25c776b75c7a89a755"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.i686-linux-gnu.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "8a00550e62a6607797ae1fc6e1f605080e3e698a"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "4d5c378a7ed669ce8573a8f3d2c5567a32a66daf7ddd383169b58902c8bfaebb"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.x86_64-linux-gnu.tar.gz"
[[iODBC]]
arch = "powerpc64le"
git-tree-sha1 = "c9e4f45480f0394c7b76667e24d1d57f8110bbe9"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "b6c6cfcff55b0565a15638d3728ac41b3f2116c81ecbe16ac20e43dc790da483"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.powerpc64le-linux-gnu.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "c87e266e18439050a204c318b67692abbc90eabf"
os = "macos"

    [[iODBC.download]]
    sha256 = "84616264df176766f147059b43c7f9e5ea35b85676a37ecfca023494597f7e3b"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.x86_64-apple-darwin14.tar.gz"
[[iODBC]]
arch = "aarch64"
git-tree-sha1 = "7f31c5f2a05d198be8233ad61bf10bf0c4a49b5e"
libc = "glibc"
os = "linux"

    [[iODBC.download]]
    sha256 = "8f7f7cf10776133dd01d557f7e9874487e048487b3801b34a14a36a1caa9db0e"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.aarch64-linux-gnu.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "f54a58c644f694a4d22607c002c7586bcd32f6ba"
os = "freebsd"

    [[iODBC.download]]
    sha256 = "a227565a392ff5b359f352a38c5e206748965b4f243fb127f1e21f1668bb1cd8"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.x86_64-unknown-freebsd11.1.tar.gz"
[[iODBC]]
arch = "x86_64"
git-tree-sha1 = "3975c3a886c3930da032d90b4341cd53b1ea0ac0"
libc = "musl"
os = "linux"

    [[iODBC.download]]
    sha256 = "8d357e839d5ba64cf77ee92943aefb8b5a842cce8d18aa2412bc981daef989f9"
    url = "https://github.com/JuliaBinaryWrappers/iODBC_jll.jl/releases/download/iODBC-v3.52.13+1/iODBC.v3.52.13.x86_64-linux-musl.tar.gz"
