## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

jobs:
 allow_failures:
   - julia: nightly
 include:
   - stage: downstream packages
     script:
       - julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
       - julia --project=. --color=yes -e 'using Pkg; Pkg.add("ImageCore"); Pkg.test("ImageCore")'


after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
