name = "MosaicViews"
uuid = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
authors = ["Christof Stocker <stocker.christof@gmail.com>"]
version = "0.2.2"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"

[compat]
OffsetArrays = "0.10, 0.11, 1"
PaddedViews = "0.4, 0.5"
julia = "1"

[extras]
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ImageCore", "ColorVectorSpace", "Test"]
