language: julia
codecov: true
coveralls: true
os:
    - linux
#   - osx # Disable to speed up CI. JuMP has no binary dependency so the result
          # with osx and linux should be similar.
julia:
    - 1.0
    # - 1.1 # Disabled to speed up CI
    # - 1.2
    # - 1.3
    - 1.4
# This is left as an example for the next big version switch.
# matrix:
#     allow_failures:
#         - julia: 0.7
branches:
  only:
    - master
    - /^release-.*$/
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
    - stage: "Examples"
      julia: 1.0
      os: linux
      script:
        - julia --project=examples -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=examples --color=yes examples/run_examples.jl
